import { httpsCallable } from "firebase/functions";
import {
  DeterministicMockAiProvider,
  aiAssistantCategoryKeys,
  buildAiAssistantCategories,
  classifyAiIntent,
  type AiAssistantCitation,
  type AiAssistantProvider,
  type AiAssistantRequest,
  type AiAssistantResponse,
} from "../domain/wave8";
import { firebaseFunctions } from "./firebase";

const fallback = new DeterministicMockAiProvider();
const platformGuide = [
  {
    key: "dashboard",
    route: "/dashboard",
    purpose: "Overview of operational status and notifications.",
  },
  {
    key: "assets",
    route: "/assets",
    purpose:
      "Register, find, edit, assign, move, label, archive and assess assets.",
  },
  {
    key: "inventory",
    route: "/inventory",
    purpose:
      "Manage stock, receipts, issues, transfers, corrections and low-stock items.",
  },
  {
    key: "assignments",
    route: "/assignments",
    purpose:
      "Assign assets and register returns with condition and digital signatures.",
  },
  {
    key: "borrows",
    route: "/borrows",
    purpose: "Request, approve, issue and return temporary loans.",
  },
  {
    key: "repairs",
    route: "/repairs",
    purpose:
      "Report faults, record progress, upload photos and complete repairs.",
  },
  {
    key: "maintenance",
    route: "/maintenance",
    purpose: "Plan recurring maintenance and record completed work.",
  },
  {
    key: "disposals",
    route: "/disposals",
    purpose: "Request, inspect, approve, complete and archive disposals.",
  },
  {
    key: "audits",
    route: "/audits",
    purpose: "Verify records, record discrepancies and corrective actions.",
  },
  {
    key: "reports",
    route: "/reports",
    purpose: "Review and export authorized reports.",
  },
  {
    key: "administration",
    route: "/administration",
    purpose:
      "Manage users, roles, reference data and access with administrator permission.",
  },
  {
    key: "account",
    route: "/account",
    purpose: "Manage profile, preferences and account information.",
  },
];
type AnthropicResult = {
  answer?: string;
  workflowKey?: string;
  citationIds?: string[];
};

export class AnthropicAiAssistantProvider implements AiAssistantProvider {
  async query(request: AiAssistantRequest): Promise<AiAssistantResponse> {
    if (!firebaseFunctions) return fallback.query(request);
    const { query, language, permissions, snapshot } = request;
    const intent = classifyAiIntent(query);
    const categories = buildAiAssistantCategories({ permissions, snapshot });
    const deniedCategories = aiAssistantCategoryKeys.filter(
      (key) => !categories.some((category) => category.key === key),
    );
    const context = {
      platformGuide,
      permittedCategories: categories.map((category) => ({
        key: category.key,
        count: category.count,
        records: category.items,
      })),
      deniedCategories,
    };
    try {
      const call = httpsCallable<
        { query: string; language: "en" | "nl"; context: typeof context },
        AnthropicResult
      >(firebaseFunctions, "askAimsAssistant");
      const { data } = await call({ query, language, context });
      const allItems = categories.flatMap((category) => category.items);
      const citations: AiAssistantCitation[] = (data.citationIds || [])
        .map((id) => allItems.find((item) => item.id === id))
        .filter((item): item is AiAssistantCitation => Boolean(item));
      return {
        intent,
        answer: String(
          data.answer ||
            (language === "nl"
              ? "Geen antwoord ontvangen."
              : "No answer received."),
        ),
        citations,
        workflow:
          categories.find((category) => category.key === data.workflowKey)
            ?.workflow ||
          platformGuide.find((module) => module.key === data.workflowKey)
            ?.route,
        mock: false,
        readOnly: true,
        blocked: false,
        limitations: [
          language === "nl"
            ? "Gegenereerd door Anthropic op basis van uw bevoegde momentopname; controleer belangrijke beslissingen."
            : "Generated by Anthropic from your permitted snapshot; verify important decisions.",
        ],
      };
    } catch (error) {
      if (import.meta.env.DEV)
        console.warn(
          "Anthropic assistant failed; using rule-based fallback.",
          error,
        );
      return fallback.query(request);
    }
  }
}

const provider = new AnthropicAiAssistantProvider();
export function createAiAssistantProvider(): AiAssistantProvider {
  return firebaseFunctions ? provider : fallback;
}
