import {lazy, type ComponentType, type LazyExoticComponent} from 'react';
import type {Permission} from '../auth/permissions';

export type RouteIcon = 'dashboard'|'assets'|'inventory'|'categories'|'locations'|'departments'|'assignments'|'borrow'|'repairs'|'maintenance'|'movements'|'audits'|'reports'|'notifications'|'assistant'|'admin'|'users'|'roles'|'activity'|'disposals'|'settings'|'install';
export type RouteStatus = 'implemented'|'partial'|'missing';
export interface AppRoute {
  id: string;
  path: string;
  component: LazyExoticComponent<ComponentType>;
  titleKey: string;
  navKey?: string;
  permission?: Permission;
  navigation: boolean;
  breadcrumb: string[];
  mobile: boolean;
  lazy: true;
  status: RouteStatus;
  icon?: RouteIcon;
  public?: boolean;
}

const page = (load: () => Promise<{default: ComponentType}>) => lazy(load);

export const routeManifest: AppRoute[] = [
  {id:'home',path:'/',component:page(()=>import('../pages/PublicLandingPage')),titleKey:'public.meta.title',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented',public:true},
  {id:'login',path:'/login',component:page(()=>import('../pages/Auth')),titleKey:'auth.login.title',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'partial',public:true},
  {id:'signup',path:'/signup',component:page(async()=>({default:(await import('../pages/Auth')).default.bind(null,{mode:'signup'})})),titleKey:'auth.register.title',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented',public:true},
  {id:'register',path:'/register',component:page(async()=>({default:(await import('../pages/Auth')).default.bind(null,{mode:'signup'})})),titleKey:'auth.register.title',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented',public:true},
  {id:'forgot',path:'/forgot-password',component:page(async()=>({default:(await import('../pages/Auth')).default.bind(null,{mode:'forgot'})})),titleKey:'auth.forgot.title',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'partial',public:true},
  {id:'verify-email',path:'/verify-email',component:page(async()=>({default:(await import('../pages/AuthFlow')).VerifyEmailPage})),titleKey:'auth.verify.title',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented',public:true},
  {id:'access-denied',path:'/access-denied',component:page(async()=>({default:(await import('../pages/AuthFlow')).AccessDeniedPage})),titleKey:'routes.forbidden',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented',public:true},
  {id:'terms',path:'/terms',component:page(()=>import('../pages/legal/TermsPage')),titleKey:'legal.terms',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented',public:true},
  {id:'privacy',path:'/privacy',component:page(()=>import('../pages/legal/PrivacyPage')),titleKey:'legal.privacy',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented',public:true},
  {id:'support',path:'/support',component:page(()=>import('../pages/legal/SupportPage')),titleKey:'legal.support',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented',public:true},
  {id:'download',path:'/download',component:page(()=>import('../pages/DownloadPage')),titleKey:'routes.download',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented',public:true},
  {id:'dashboard',path:'/dashboard',component:page(()=>import('../pages/Dashboard')),titleKey:'routes.dashboard',navKey:'nav.dashboard',permission:'dashboard.view',navigation:true,breadcrumb:['routes.dashboard'],mobile:true,lazy:true,status:'partial',icon:'dashboard'},
  {id:'assets',path:'/assets',component:page(()=>import('../pages/Assets')),titleKey:'routes.assets',navKey:'nav.assets',permission:'assets.view',navigation:true,breadcrumb:['routes.assets'],mobile:true,lazy:true,status:'implemented',icon:'assets'},
  {id:'asset-new',path:'/assets/new',component:page(()=>import('../pages/AssetForm')),titleKey:'routes.assetNew',permission:'assets.create',navigation:false,breadcrumb:['routes.assets','routes.assetNew'],mobile:true,lazy:true,status:'implemented'},
  {id:'asset-import',path:'/assets/import',component:page(()=>import('../pages/CombinedAssetImport')),titleKey:'routes.assetImport',permission:'assets.import',navigation:false,breadcrumb:['routes.assets','routes.assetImport'],mobile:true,lazy:true,status:'implemented'},
  {id:'asset-edit',path:'/assets/:assetId/edit',component:page(()=>import('../pages/AssetForm')),titleKey:'routes.assetDetail',permission:'assets.edit',navigation:false,breadcrumb:['routes.assets','routes.assetDetail'],mobile:true,lazy:true,status:'implemented'},
  {id:'asset-history',path:'/assets/:assetId/history',component:page(async()=>({default:(await import('../pages/AssetModule')).AssetHistory})),titleKey:'routes.assetHistory',permission:'assets.view',navigation:false,breadcrumb:['routes.assets','routes.assetDetail','routes.assetHistory'],mobile:true,lazy:true,status:'implemented'},
  {id:'asset-assign',path:'/assets/:assetId/assign',component:page(async()=>({default:(await import('../pages/AssetModule')).AssetAssignment})),titleKey:'routes.assetAssign',permission:'assignments.manage',navigation:false,breadcrumb:['routes.assets','routes.assetDetail','routes.assetAssign'],mobile:true,lazy:true,status:'implemented'},
  {id:'asset-move',path:'/assets/:assetId/move',component:page(async()=>({default:(await import('../pages/AssetModule')).AssetMovement})),titleKey:'routes.assetMove',permission:'movements.manage',navigation:false,breadcrumb:['routes.assets','routes.assetDetail','routes.assetMove'],mobile:true,lazy:true,status:'implemented'},
  {id:'asset-labels',path:'/assets/:assetId/labels',component:page(async()=>({default:(await import('../pages/AssetModule')).AssetLabels})),titleKey:'routes.assetLabels',permission:'assets.view',navigation:false,breadcrumb:['routes.assets','routes.assetDetail','routes.assetLabels'],mobile:true,lazy:true,status:'implemented'},
  {id:'asset-disposal',path:'/assets/:assetId/disposal',component:page(async()=>({default:(await import('../pages/AssetModule')).AssetDisposal})),titleKey:'routes.assetDisposal',permission:'disposals.request',navigation:false,breadcrumb:['routes.assets','routes.assetDetail','routes.assetDisposal'],mobile:true,lazy:true,status:'implemented'},
  {id:'asset-detail',path:'/assets/:assetId',component:page(()=>import('../pages/AssetDetail')),titleKey:'routes.assetDetail',permission:'assets.view',navigation:false,breadcrumb:['routes.assets','routes.assetDetail'],mobile:true,lazy:true,status:'implemented'},
  {id:'inventory',path:'/inventory',component:page(async()=>({default:(await import('../pages/InventoryWave3')).InventoryList})),titleKey:'routes.inventory',navKey:'nav.inventory',permission:'inventory.view',navigation:true,breadcrumb:['routes.inventory'],mobile:true,lazy:true,status:'implemented',icon:'inventory'},
  {id:'inventory-new',path:'/inventory/new',component:page(async()=>({default:(await import('../pages/InventoryWave3')).InventoryForm})),titleKey:'routes.inventory',permission:'inventory.create',navigation:false,breadcrumb:['routes.inventory'],mobile:true,lazy:true,status:'implemented'},
  {id:'inventory-import',path:'/inventory/import',component:page(async()=>({default:(await import('../pages/InventoryWave3')).InventoryImport})),titleKey:'routes.inventory',permission:'inventory.create',navigation:false,breadcrumb:['routes.inventory'],mobile:true,lazy:true,status:'implemented'},
  {id:'inventory-edit',path:'/inventory/:itemId/edit',component:page(async()=>({default:(await import('../pages/InventoryWave3')).InventoryForm})),titleKey:'routes.inventory',permission:'inventory.edit',navigation:false,breadcrumb:['routes.inventory'],mobile:true,lazy:true,status:'implemented'},
  {id:'inventory-receive',path:'/inventory/receive',component:page(async()=>({default:(await import('../pages/InventoryWave3')).ReceiveStock})),titleKey:'routes.inventory',permission:'inventory.receive',navigation:false,breadcrumb:['routes.inventory'],mobile:true,lazy:true,status:'implemented'},
  {id:'inventory-issue',path:'/inventory/issue',component:page(async()=>({default:(await import('../pages/InventoryWave3')).IssueStock})),titleKey:'routes.inventory',permission:'inventory.issue',navigation:false,breadcrumb:['routes.inventory'],mobile:true,lazy:true,status:'implemented'},
  {id:'inventory-transfer',path:'/inventory/transfer',component:page(async()=>({default:(await import('../pages/InventoryWave3')).TransferStock})),titleKey:'routes.inventory',permission:'inventory.transfer',navigation:false,breadcrumb:['routes.inventory'],mobile:true,lazy:true,status:'implemented'},
  {id:'inventory-return',path:'/inventory/return',component:page(async()=>({default:(await import('../pages/InventoryWave3')).ReturnStock})),titleKey:'routes.inventory',permission:'inventory.return',navigation:false,breadcrumb:['routes.inventory'],mobile:true,lazy:true,status:'implemented'},
  {id:'inventory-correct',path:'/inventory/correct',component:page(async()=>({default:(await import('../pages/InventoryWave3')).CorrectStock})),titleKey:'routes.inventory',permission:'inventory.correct',navigation:false,breadcrumb:['routes.inventory'],mobile:true,lazy:true,status:'implemented'},
  {id:'inventory-reservations',path:'/inventory/reservations',component:page(async()=>({default:(await import('../pages/InventoryWave3')).Reservations})),titleKey:'routes.inventory',permission:'inventory.reserve',navigation:false,breadcrumb:['routes.inventory'],mobile:true,lazy:true,status:'implemented'},
  {id:'inventory-low-stock',path:'/inventory/low-stock',component:page(async()=>({default:(await import('../pages/InventoryWave3')).LowStock})),titleKey:'routes.inventory',permission:'inventory.view',navigation:false,breadcrumb:['routes.inventory'],mobile:true,lazy:true,status:'implemented'},
  {id:'inventory-detail',path:'/inventory/:itemId',component:page(async()=>({default:(await import('../pages/InventoryWave3')).InventoryDetail})),titleKey:'routes.inventory',permission:'inventory.view',navigation:false,breadcrumb:['routes.inventory'],mobile:true,lazy:true,status:'implemented'},
  {id:'categories',path:'/categories',component:page(async()=>({default:(await import('../pages/ReferenceData')).CategoriesPage})),titleKey:'routes.categories',navKey:'nav.categories',permission:'categories.manage',navigation:true,breadcrumb:['routes.categories'],mobile:true,lazy:true,status:'implemented',icon:'categories'},
  {id:'category-new',path:'/categories/new',component:page(async()=>({default:(await import('../pages/ReferenceData')).CategoriesPage})),titleKey:'routes.categories',permission:'categories.manage',navigation:false,breadcrumb:['routes.categories'],mobile:true,lazy:true,status:'implemented'},
  {id:'category-edit',path:'/categories/:categoryId/edit',component:page(async()=>({default:(await import('../pages/ReferenceData')).CategoriesPage})),titleKey:'routes.categories',permission:'categories.manage',navigation:false,breadcrumb:['routes.categories'],mobile:true,lazy:true,status:'implemented'},
  {id:'category-detail',path:'/categories/:categoryId',component:page(async()=>({default:(await import('../pages/ReferenceData')).CategoriesPage})),titleKey:'routes.categories',permission:'categories.manage',navigation:false,breadcrumb:['routes.categories'],mobile:true,lazy:true,status:'implemented'},
  {id:'locations',path:'/locations',component:page(async()=>({default:(await import('../pages/ReferenceData')).LocationsPage})),titleKey:'routes.locations',navKey:'nav.locations',permission:'locations.manage',navigation:true,breadcrumb:['routes.locations'],mobile:true,lazy:true,status:'implemented',icon:'locations'},
  {id:'location-new',path:'/locations/new',component:page(async()=>({default:(await import('../pages/ReferenceData')).LocationsPage})),titleKey:'routes.locations',permission:'locations.manage',navigation:false,breadcrumb:['routes.locations'],mobile:true,lazy:true,status:'implemented'},
  {id:'location-edit',path:'/locations/:locationId/edit',component:page(async()=>({default:(await import('../pages/ReferenceData')).LocationsPage})),titleKey:'routes.locations',permission:'locations.manage',navigation:false,breadcrumb:['routes.locations'],mobile:true,lazy:true,status:'implemented'},
  {id:'location-detail',path:'/locations/:locationId',component:page(async()=>({default:(await import('../pages/ReferenceData')).LocationsPage})),titleKey:'routes.locations',permission:'locations.manage',navigation:false,breadcrumb:['routes.locations'],mobile:true,lazy:true,status:'implemented'},
  {id:'departments',path:'/departments',component:page(async()=>({default:(await import('../pages/ReferenceData')).DepartmentsPage})),titleKey:'routes.departments',navKey:'nav.departments',permission:'departments.manage',navigation:true,breadcrumb:['routes.departments'],mobile:true,lazy:true,status:'implemented',icon:'departments'},
  {id:'department-new',path:'/departments/new',component:page(async()=>({default:(await import('../pages/ReferenceData')).DepartmentsPage})),titleKey:'routes.departments',permission:'departments.manage',navigation:false,breadcrumb:['routes.departments'],mobile:true,lazy:true,status:'implemented'},
  {id:'department-edit',path:'/departments/:departmentId/edit',component:page(async()=>({default:(await import('../pages/ReferenceData')).DepartmentsPage})),titleKey:'routes.departments',permission:'departments.manage',navigation:false,breadcrumb:['routes.departments'],mobile:true,lazy:true,status:'implemented'},
  {id:'department-detail',path:'/departments/:departmentId',component:page(async()=>({default:(await import('../pages/ReferenceData')).DepartmentsPage})),titleKey:'routes.departments',permission:'departments.manage',navigation:false,breadcrumb:['routes.departments'],mobile:true,lazy:true,status:'implemented'},
  {id:'users',path:'/users',component:page(()=>import('../pages/UserDirectory')),titleKey:'routes.users',navKey:'nav.users',permission:'users.manage',navigation:true,breadcrumb:['routes.users'],mobile:true,lazy:true,status:'implemented',icon:'users'},
  {id:'assignments',path:'/assignments',component:page(()=>import('../pages/Assignments')),titleKey:'routes.assignments',navKey:'nav.assignments',permission:'assignments.manage',navigation:true,breadcrumb:['routes.assignments'],mobile:true,lazy:true,status:'implemented',icon:'assignments'},
  {id:'assignment-new',path:'/assignments/new',component:page(()=>import('../pages/Assignments')),titleKey:'routes.assignments',permission:'assignments.manage',navigation:false,breadcrumb:['routes.assignments'],mobile:true,lazy:true,status:'implemented'},
  {id:'assignment-edit',path:'/assignments/:assignmentId/edit',component:page(()=>import('../pages/Assignments')),titleKey:'routes.assignments',permission:'assignments.manage',navigation:false,breadcrumb:['routes.assignments'],mobile:true,lazy:true,status:'implemented'},
  {id:'assignment-return',path:'/assignments/:assignmentId/return',component:page(()=>import('../pages/Assignments')),titleKey:'routes.assignments',permission:'assignments.manage',navigation:false,breadcrumb:['routes.assignments'],mobile:true,lazy:true,status:'implemented'},
  {id:'assignment-history',path:'/assignments/:assignmentId/history',component:page(()=>import('../pages/Assignments')),titleKey:'routes.assignments',permission:'assignments.manage',navigation:false,breadcrumb:['routes.assignments'],mobile:true,lazy:true,status:'implemented'},
  {id:'assignment-detail',path:'/assignments/:assignmentId',component:page(()=>import('../pages/Assignments')),titleKey:'routes.assignments',permission:'assignments.manage',navigation:false,breadcrumb:['routes.assignments'],mobile:true,lazy:true,status:'implemented'},
  {id:'borrows',path:'/borrows',component:page(()=>import('../pages/Borrow')),titleKey:'routes.borrow',navKey:'nav.borrow',permission:'borrow.manage',navigation:true,breadcrumb:['routes.borrow'],mobile:true,lazy:true,status:'implemented',icon:'borrow'},
  {id:'borrows-new',path:'/borrows/new',component:page(()=>import('../pages/Borrow')),titleKey:'routes.borrowNew',permission:'borrow.manage',navigation:false,breadcrumb:['routes.borrow','routes.borrowNew'],mobile:true,lazy:true,status:'implemented'},
  {id:'borrows-overdue',path:'/borrows/overdue',component:page(async()=>({default:(await import('../pages/Borrow')).BorrowOverduePage})),titleKey:'routes.borrow',permission:'borrow.manage',navigation:false,breadcrumb:['routes.borrow'],mobile:true,lazy:true,status:'implemented'},
  {id:'borrow-edit',path:'/borrows/:borrowId/edit',component:page(()=>import('../pages/Borrow')),titleKey:'routes.borrowDetail',permission:'borrow.manage',navigation:false,breadcrumb:['routes.borrow','routes.borrowDetail'],mobile:true,lazy:true,status:'implemented'},
  {id:'borrow-approve',path:'/borrows/:borrowId/approve',component:page(()=>import('../pages/Borrow')),titleKey:'routes.borrowDetail',permission:'borrow.manage',navigation:false,breadcrumb:['routes.borrow','routes.borrowDetail'],mobile:true,lazy:true,status:'implemented'},
  {id:'borrow-issue',path:'/borrows/:borrowId/issue',component:page(()=>import('../pages/Borrow')),titleKey:'routes.borrowDetail',permission:'borrow.manage',navigation:false,breadcrumb:['routes.borrow','routes.borrowDetail'],mobile:true,lazy:true,status:'implemented'},
  {id:'borrow-return',path:'/borrows/:borrowId/return',component:page(()=>import('../pages/Borrow')),titleKey:'routes.borrowDetail',permission:'borrow.manage',navigation:false,breadcrumb:['routes.borrow','routes.borrowDetail'],mobile:true,lazy:true,status:'implemented'},
  {id:'borrow-history',path:'/borrows/:borrowId/history',component:page(()=>import('../pages/Borrow')),titleKey:'routes.borrowDetail',permission:'borrow.manage',navigation:false,breadcrumb:['routes.borrow','routes.borrowDetail'],mobile:true,lazy:true,status:'implemented'},
  {id:'borrow-detail',path:'/borrows/:borrowId',component:page(()=>import('../pages/Borrow')),titleKey:'routes.borrowDetail',permission:'borrow.manage',navigation:false,breadcrumb:['routes.borrow','routes.borrowDetail'],mobile:true,lazy:true,status:'implemented'},
  {id:'borrow-legacy',path:'/borrow',component:page(()=>import('../pages/Borrow')),titleKey:'routes.borrow',permission:'borrow.manage',navigation:false,breadcrumb:['routes.borrow'],mobile:true,lazy:true,status:'implemented'},
  {id:'borrow-new-legacy',path:'/borrow/new',component:page(()=>import('../pages/Borrow')),titleKey:'routes.borrowNew',permission:'borrow.manage',navigation:false,breadcrumb:['routes.borrow','routes.borrowNew'],mobile:true,lazy:true,status:'implemented'},
  {id:'borrow-detail-legacy',path:'/borrow/:id',component:page(()=>import('../pages/Borrow')),titleKey:'routes.borrowDetail',permission:'borrow.manage',navigation:false,breadcrumb:['routes.borrow','routes.borrowDetail'],mobile:true,lazy:true,status:'implemented'},
  {id:'repairs',path:'/repairs',component:page(()=>import('../pages/Repairs')),titleKey:'routes.repairs',navKey:'nav.repairs',permission:'repairs.manage',navigation:true,breadcrumb:['routes.repairs'],mobile:true,lazy:true,status:'implemented',icon:'repairs'},
  {id:'repair-new',path:'/repairs/new',component:page(()=>import('../pages/Repairs')),titleKey:'routes.repairs',permission:'repairs.manage',navigation:false,breadcrumb:['routes.repairs'],mobile:true,lazy:true,status:'implemented'},
  ...(['edit','diagnosis','approval','parts','testing','complete','return','history'].map(action=>({id:`repair-${action}`,path:`/repairs/:repairId/${action}`,component:page(()=>import('../pages/Repairs')),titleKey:'routes.repairDetail',permission:'repairs.manage',navigation:false,breadcrumb:['routes.repairs','routes.repairDetail'],mobile:true,lazy:true,status:'implemented'})) as AppRoute[]),
  {id:'repair-detail',path:'/repairs/:repairId',component:page(()=>import('../pages/Repairs')),titleKey:'routes.repairDetail',permission:'repairs.manage',navigation:false,breadcrumb:['routes.repairs','routes.repairDetail'],mobile:true,lazy:true,status:'implemented'},
  {id:'maintenance',path:'/maintenance',component:page(()=>import('../pages/Maintenance')),titleKey:'routes.maintenance',navKey:'nav.maintenance',permission:'maintenance.manage',navigation:true,breadcrumb:['routes.maintenance'],mobile:true,lazy:true,status:'implemented',icon:'maintenance'},
  ...(['calendar','schedules','schedules/new','upcoming','overdue'].map(action=>({id:`maintenance-${action.replace('/','-')}`,path:`/maintenance/${action}`,component:page(()=>import('../pages/Maintenance')),titleKey:'routes.maintenance',permission:'maintenance.manage',navigation:false,breadcrumb:['routes.maintenance'],mobile:true,lazy:true,status:'implemented'})) as AppRoute[]),
  ...(['schedules/:scheduleId/edit','schedules/:scheduleId',':maintenanceId/perform',':maintenanceId/complete',':maintenanceId/history',':maintenanceId'].map(action=>({id:`maintenance-${action.replaceAll('/','-').replaceAll(':','')}`,path:`/maintenance/${action}`,component:page(()=>import('../pages/Maintenance')),titleKey:'routes.maintenance',permission:'maintenance.manage',navigation:false,breadcrumb:['routes.maintenance'],mobile:true,lazy:true,status:'implemented'})) as AppRoute[]),
  {id:'movements',path:'/movements',component:page(()=>import('../pages/Movements')),titleKey:'routes.movements',navKey:'nav.movements',permission:'movements.manage',navigation:true,breadcrumb:['routes.movements'],mobile:true,lazy:true,status:'implemented',icon:'movements'},
  {id:'movement-new',path:'/movements/new',component:page(()=>import('../pages/Movements')),titleKey:'routes.movementNew',permission:'movements.manage',navigation:false,breadcrumb:['routes.movements','routes.movementNew'],mobile:true,lazy:true,status:'implemented'},
  {id:'movement-corrections',path:'/movements/corrections',component:page(()=>import('../pages/Movements')),titleKey:'routes.movements',permission:'movements.manage',navigation:false,breadcrumb:['routes.movements'],mobile:true,lazy:true,status:'implemented'},
  {id:'movement-transfers',path:'/movements/transfers',component:page(()=>import('../pages/Movements')),titleKey:'routes.movements',permission:'movements.manage',navigation:false,breadcrumb:['routes.movements'],mobile:true,lazy:true,status:'implemented'},
  {id:'movement-history',path:'/movements/:movementId/history',component:page(()=>import('../pages/Movements')),titleKey:'routes.movements',permission:'movements.manage',navigation:false,breadcrumb:['routes.movements'],mobile:true,lazy:true,status:'implemented'},
  {id:'movement-detail',path:'/movements/:movementId',component:page(()=>import('../pages/Movements')),titleKey:'routes.movements',permission:'movements.manage',navigation:false,breadcrumb:['routes.movements'],mobile:true,lazy:true,status:'implemented'},
  {id:'audits',path:'/audits',component:page(()=>import('../pages/Audits')),titleKey:'routes.audits',navKey:'nav.audits',permission:'audits.view',navigation:true,breadcrumb:['routes.audits'],mobile:true,lazy:true,status:'partial',icon:'audits'},
  {id:'audit-new',path:'/audits/new',component:page(()=>import('../pages/Audits')),titleKey:'routes.auditNew',permission:'audits.perform',navigation:false,breadcrumb:['routes.audits','routes.auditNew'],mobile:true,lazy:true,status:'partial'},
  ...(['upcoming','in-progress','overdue','discrepancies','corrective-actions'].map(action=>({id:`audits-${action}`,path:`/audits/${action}`,component:page(()=>import('../pages/Audits')),titleKey:'routes.audits',permission:'audits.view',navigation:false,breadcrumb:['routes.audits'],mobile:true,lazy:true,status:'partial'})) as AppRoute[]),
  ...(['edit','prepare','generate','execute','review','results','discrepancies','corrective-actions','report','history'].map(action=>({id:`audit-${action}`,path:`/audits/:auditId/${action}`,component:page(()=>import('../pages/Audits')),titleKey:'routes.auditDetail',permission:'audits.perform',navigation:false,breadcrumb:['routes.audits','routes.auditDetail'],mobile:true,lazy:true,status:'partial'})) as AppRoute[]),
  {id:'audit-detail',path:'/audits/:auditId',component:page(()=>import('../pages/Audits')),titleKey:'routes.auditDetail',permission:'audits.perform',navigation:false,breadcrumb:['routes.audits','routes.auditDetail'],mobile:true,lazy:true,status:'partial'},
  {id:'reports',path:'/reports',component:page(()=>import('../pages/Reports')),titleKey:'routes.reports',navKey:'nav.reports',permission:'reports.view',navigation:true,breadcrumb:['routes.reports'],mobile:true,lazy:true,status:'partial',icon:'reports'},
  {id:'audit-trail',path:'/reports/audit-trail',component:page(async()=>({default:(await import('../pages/Reports')).AuditTrailPage})),titleKey:'routes.activity',permission:'reports.view',navigation:false,breadcrumb:['routes.reports','routes.activity'],mobile:true,lazy:true,status:'implemented'},
  ...(['assets','inventory','assignments','borrows','overdue-equipment','repairs','maintenance','movements','audits','discrepancies','corrective-actions','disposals','warranties','low-stock','monthly','custom','scheduled'].map(action=>({id:`reports-${action}`,path:`/reports/${action}`,component:page(()=>import('../pages/Reports')),titleKey:'routes.reports',permission:'reports.view',navigation:false,breadcrumb:['routes.reports'],mobile:true,lazy:true,status:'partial'})) as AppRoute[]),
  ...(['preview','history'].map(action=>({id:`report-${action}`,path:`/reports/:reportId/${action}`,component:page(()=>import('../pages/Reports')),titleKey:'routes.reports',permission:'reports.view',navigation:false,breadcrumb:['routes.reports'],mobile:true,lazy:true,status:'partial'})) as AppRoute[]),
  {id:'notifications',path:'/notifications',component:page(async()=>({default:(await import('../pages/Administration')).NotificationsPage})),titleKey:'routes.notifications',navKey:'nav.notifications',permission:'notifications.view',navigation:true,breadcrumb:['routes.notifications'],mobile:true,lazy:true,status:'partial',icon:'notifications'},
  ...(['preferences','history','escalations'].map(action=>({id:`notifications-${action}`,path:`/notifications/${action}`,component:page(async()=>({default:(await import('../pages/Administration')).NotificationsPage})),titleKey:'routes.notifications',permission:'notifications.view',navigation:false,breadcrumb:['routes.notifications'],mobile:true,lazy:true,status:'partial'})) as AppRoute[]),
  {id:'management',path:'/management',component:page(()=>import('../pages/Reports')),titleKey:'routes.reports',permission:'reports.view',navigation:false,breadcrumb:['routes.reports'],mobile:true,lazy:true,status:'partial'},
  ...(['assets','inventory','service','audits','lifecycle','risks'].map(action=>({id:`management-${action}`,path:`/management/${action}`,component:page(()=>import('../pages/Reports')),titleKey:'routes.reports',permission:'reports.view',navigation:false,breadcrumb:['routes.reports'],mobile:true,lazy:true,status:'partial'})) as AppRoute[]),
  ...(['history','saved','settings',':conversationId'].map(action=>({id:`assistant-${action.replace(':','')}`,path:`/assistant/${action}`,component:page(()=>import('../pages/Assistant')),titleKey:'routes.assistant',permission:'assistant.use',navigation:false,breadcrumb:['routes.assistant'],mobile:true,lazy:true,status:'partial'})) as AppRoute[]),
  {id:'assistant',path:'/assistant',component:page(()=>import('../pages/Assistant')),titleKey:'routes.assistant',navKey:'nav.assistant',permission:'assistant.use',navigation:true,breadcrumb:['routes.assistant'],mobile:true,lazy:true,status:'partial',icon:'assistant'},
  {id:'admin',path:'/admin',component:page(()=>import('../pages/AdminConsole')),titleKey:'routes.admin',navKey:'nav.admin',permission:'admin.access',navigation:false,breadcrumb:['routes.admin'],mobile:true,lazy:true,status:'implemented',icon:'admin'},
  {id:'admin-users',path:'/admin/users/*',component:page(async()=>({default:(await import('../pages/Administration')).UsersPage})),titleKey:'routes.users',permission:'admin.users.manage',navigation:false,breadcrumb:['routes.admin','routes.users'],mobile:true,lazy:true,status:'implemented'},
  {id:'admin-roles',path:'/admin/roles-permissions/*',component:page(async()=>({default:(await import('../pages/Administration')).RolesPage})),titleKey:'routes.roles',permission:'admin.roles.manage',navigation:false,breadcrumb:['routes.admin','routes.roles'],mobile:true,lazy:true,status:'implemented'},
  {id:'admin-activity',path:'/admin/activity-log/*',component:page(async()=>({default:(await import('../pages/Administration')).ActivityPage})),titleKey:'routes.activity',permission:'admin.audit.read',navigation:false,breadcrumb:['routes.admin','routes.activity'],mobile:true,lazy:true,status:'implemented'},
  {id:'admin-settings',path:'/admin/settings/*',component:page(()=>import('../pages/Settings')),titleKey:'routes.settings',navKey:'nav.settings',permission:'admin.system.configure',navigation:false,breadcrumb:['routes.admin','routes.settings'],mobile:true,lazy:true,status:'implemented',icon:'settings'},
  ...(['new',':userId/edit',':userId/access',':userId/activity',':userId/sessions',':userId'].map(action=>({id:`users-${action.replaceAll('/','-').replace(':','')}`,path:`/users/${action}`,component:page(async()=>({default:(await import('../pages/Administration')).UsersPage})),titleKey:'routes.users',permission:'users.manage',navigation:false,breadcrumb:['routes.users'],mobile:true,lazy:true,status:'partial'})) as AppRoute[]),
  ...(['new',':roleId/edit',':roleId/permissions',':roleId'].map(action=>({id:`roles-${action.replaceAll('/','-').replace(':','')}`,path:`/roles/${action}`,component:page(async()=>({default:(await import('../pages/Administration')).RolesPage})),titleKey:'routes.roles',permission:'roles.manage',navigation:false,breadcrumb:['routes.roles'],mobile:true,lazy:true,status:'partial'})) as AppRoute[]),
  {id:'roles',path:'/roles',component:page(async()=>({default:(await import('../pages/System')).LegacyRolesRedirect})),titleKey:'routes.roles',permission:'admin.roles.manage',navigation:false,breadcrumb:['routes.roles'],mobile:true,lazy:true,status:'implemented'},
  ...(['permissions','permissions/matrix','permissions/simulator','access-reviews'].map(action=>({id:action.replace('/','-'),path:`/${action}`,component:page(async()=>({default:(await import('../pages/Administration')).RolesPage})),titleKey:'routes.roles',permission:'roles.manage',navigation:false,breadcrumb:['routes.roles'],mobile:true,lazy:true,status:'partial'})) as AppRoute[]),
  ...(['authentication','security','exports','settings','ai',':activityId'].map(action=>({id:`activity-${action.replace(':','')}`,path:`/activity/${action}`,component:page(async()=>({default:(await import('../pages/Administration')).ActivityPage})),titleKey:'routes.activity',permission:'activity.view',navigation:false,breadcrumb:['routes.activity'],mobile:true,lazy:true,status:'partial'})) as AppRoute[]),
  {id:'activity',path:'/activity',component:page(async()=>({default:(await import('../pages/System')).LegacyActivityRedirect})),titleKey:'routes.activity',permission:'admin.audit.read',navigation:false,breadcrumb:['routes.activity'],mobile:true,lazy:true,status:'implemented'},
  {id:'disposals',path:'/disposals',component:page(()=>import('../pages/Disposals')),titleKey:'routes.disposals',navKey:'nav.disposals',permission:'disposals.view',navigation:true,breadcrumb:['routes.disposals'],mobile:true,lazy:true,status:'implemented',icon:'disposals'},
  {id:'disposal-new',path:'/disposals/new',component:page(()=>import('../pages/Disposals')),titleKey:'routes.disposalNew',permission:'disposals.request',navigation:false,breadcrumb:['routes.disposals','routes.disposalNew'],mobile:true,lazy:true,status:'partial'},
  {id:'disposal-detail',path:'/disposals/:id',component:page(()=>import('../pages/Disposals')),titleKey:'routes.disposalDetail',permission:'disposals.view',navigation:false,breadcrumb:['routes.disposals','routes.disposalDetail'],mobile:true,lazy:true,status:'partial'},
  {id:'settings',path:'/settings/*',component:page(()=>import('../pages/Settings')),titleKey:'routes.settings',navKey:'nav.settings',navigation:true,breadcrumb:['routes.settings'],mobile:true,lazy:true,status:'implemented',icon:'settings'},
  {id:'profile',path:'/profile',component:page(async()=>({default:(await import('../pages/Account')).ProfilePage})),titleKey:'routes.settings',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented'},
  {id:'preferences',path:'/preferences',component:page(async()=>({default:(await import('../pages/Account')).PreferencesPage})),titleKey:'routes.settings',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented'},
  {id:'security',path:'/security',component:page(async()=>({default:(await import('../pages/AuthFlow')).SecurityPage})),titleKey:'routes.settings',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented'},
  {id:'help',path:'/help',component:page(async()=>({default:(await import('../pages/AuthFlow')).HelpPage})),titleKey:'legal.support',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented'},
  {id:'offline',path:'/offline',component:page(async()=>({default:(await import('../pages/System')).Offline})),titleKey:'routes.offline',navigation:false,breadcrumb:['routes.offline'],mobile:true,lazy:true,status:'partial'},
  {id:'forbidden',path:'/403',component:page(async()=>({default:(await import('../pages/System')).Forbidden})),titleKey:'routes.forbidden',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented'},
  {id:'not-found',path:'*',component:page(async()=>({default:(await import('../pages/System')).NotFound})),titleKey:'routes.notFound',navigation:false,breadcrumb:[],mobile:true,lazy:true,status:'implemented'}
];

export const navRoutes = routeManifest.filter(route => route.navigation);
export const rootRedirect = '/';
export const matchRoute = (pathname: string) => routeManifest.find(route => {
  if(route.path.endsWith('/*')){
    const base=route.path.slice(0,-2);
    return pathname===base||pathname.startsWith(`${base}/`);
  }
  const pattern = route.path.replace(/:[^/]+/g,'[^/]+').replace('*','.*');
  return new RegExp(`^${pattern}$`).test(pathname);
});
