import {Activity,BarChart3,Boxes,Menu,PackageCheck,Plus,ScanLine,Search,Settings,Wrench} from 'lucide-react';
import type {CSSProperties,ReactNode} from 'react';
import {aimsLandingCopy} from '../../content/aimsLanding';

type Language='en'|'nl';
type DeviceType='desktop'|'laptop'|'tablet'|'mobile';
type FrameProps={deviceType:DeviceType;screenWidth:number;screenHeight:number;screenRadius:number;screenInset:number;bezelWidth:number;orientation?:'landscape'|'portrait';objectPosition?:string;label:string;children:ReactNode;className?:string};
export function DeviceFrame({deviceType,screenWidth,screenHeight,screenRadius,screenInset,bezelWidth,orientation='landscape',objectPosition='center',label,children,className=''}:FrameProps){
 const style={'--screen-width':screenWidth,'--screen-height':screenHeight,'--screen-radius':`${screenRadius}px`,'--screen-inset':`${screenInset}px`,'--bezel-width':`${bezelWidth}px`,'--object-position':objectPosition} as CSSProperties;
 return <figure className={`aims-device-frame aims-device-frame--${deviceType} aims-device-frame--${orientation} ${className}`.trim()} style={style} aria-label={label} data-device={deviceType}><div className="aims-device-shell"><div className="aims-device-camera" aria-hidden="true"/><div className="aims-device-screen">{children}</div></div>{deviceType==='desktop'&&<><span className="aims-monitor-neck"/><span className="aims-monitor-base"/></>}{deviceType==='laptop'&&<div className="aims-laptop-base"><span/></div>}</figure>;
}

const metrics=[['total','1,248'],['available','274'],['assigned','892'],['maintenance','82']] as const;
const navIcons=[Boxes,PackageCheck,Wrench,BarChart3,Settings];
function Sidebar(){return <aside className="aims-preview-sidebar"><b>AIMS</b>{navIcons.map((Icon,index)=><span className={index===0?'active':''} key={index}><Icon/></span>)}</aside>}
function Kpis({language,limit=4,skip=0}:{language:Language;limit?:number;skip?:number}){const p=aimsLandingCopy[language].preview;return <div className="aims-preview-kpis">{metrics.slice(skip,skip+limit).map(([key,value])=><article key={key}><small>{p[key]}</small><strong>{value}</strong><i/></article>)}</div>}
function Bars(){return <div className="aims-preview-bars" aria-hidden="true">{[42,65,48,82,61,92,74].map((height,index)=><i key={index} style={{height:`${height}%`}}/>)}</div>}
function Donut(){return <div className="aims-preview-donut" aria-hidden="true"><span>1,248</span></div>}
function ActivityList({language,short=false}:{language:Language;short?:boolean}){const labels=language==='nl'?['Laptop toegewezen','Projector retour','Onderhoud gepland','Audit voltooid']:['Laptop assigned','Projector returned','Maintenance scheduled','Audit completed'];return <div className="aims-preview-list">{labels.slice(0,short?3:4).map((label,index)=><span key={label}><i className={`tone-${index}`}/><b>{label}</b><small>{index+1}h</small></span>)}</div>}
function Topbar({language}:{language:Language}){const p=aimsLandingCopy[language].preview;return <header className="aims-preview-topbar"><div><small>AIMS</small><b>{p.dashboard}</b></div><label><Search/><span>{p.search}</span></label><span className="aims-preview-user">AM</span></header>}

export function DashboardPreviewDesktop({language,condensed=false}:{language:Language;condensed?:boolean}){const p=aimsLandingCopy[language].preview;return <div className={`aims-preview-app aims-preview-app--desktop ${condensed?'is-condensed':''}`}><Sidebar/><main><Topbar language={language}/><Kpis language={language}/><div className="aims-preview-main-grid"><article><b>{p.movement}</b><Bars/></article><article><b>{p.status}</b><Donut/></article><article><b>{p.activity}</b><ActivityList language={language}/></article></div><div className="aims-preview-bottom"><article><b>{p.table}</b><table><tbody><tr><td>ICT-0248</td><td>Laptop</td><td>{p.assigned}</td></tr><tr><td>FUR-0103</td><td>Desk</td><td>{p.available}</td></tr></tbody></table></article><article><b>{p.actions}</b><span><Plus/>{p.add}</span><span><ScanLine/>{p.scan}</span></article></div></main></div>}

export function DashboardPreviewTablet({language}:{language:Language}){const p=aimsLandingCopy[language].preview;return <div className="aims-preview-app aims-preview-app--tablet"><header><b>AIMS</b><Menu/><span>AM</span></header><main><h3>{p.dashboard}</h3><Kpis language={language}/><div className="aims-tablet-grid"><article><b>{p.status}</b><Donut/></article><article><b>{p.activity}</b><ActivityList language={language} short/></article></div><div className="aims-touch-actions"><span><Plus/>{p.add}</span><span><ScanLine/>{p.scan}</span></div></main></div>}

export function DashboardPreviewMobile({language}:{language:Language}){const p=aimsLandingCopy[language].preview;return <div className="aims-preview-app aims-preview-app--mobile"><header><b>AIMS</b><span>AM</span></header><main><small>{p.dashboard}</small><h3>{p.total}</h3><strong className="aims-mobile-total">1,248</strong><Kpis language={language} limit={2} skip={1}/><article className="aims-mobile-overview"><b>{p.status}</b><Bars/></article><article><b>{p.activity}</b><ActivityList language={language} short/></article><button type="button"><ScanLine/>{p.scan}</button></main><nav><span><Boxes/>{p.navHome}</span><span><PackageCheck/>{p.navAssets}</span><span><ScanLine/>{p.navScan}</span><span><Activity/>{p.navMore}</span></nav></div>}

export function AimsDeviceShowcase({language}:{language:Language}){const p=aimsLandingCopy[language].preview;return <div className="aims-device-stage"><DeviceFrame deviceType="desktop" screenWidth={16} screenHeight={9} screenRadius={10} screenInset={10} bezelWidth={10} label={p.desktop} className="aims-stage-desktop"><DashboardPreviewDesktop language={language}/></DeviceFrame><DeviceFrame deviceType="laptop" screenWidth={16} screenHeight={10} screenRadius={8} screenInset={8} bezelWidth={8} label={p.laptop} className="aims-stage-laptop"><DashboardPreviewDesktop language={language} condensed/></DeviceFrame><DeviceFrame deviceType="tablet" screenWidth={4} screenHeight={3} screenRadius={12} screenInset={9} bezelWidth={9} label={p.tablet} className="aims-stage-tablet"><DashboardPreviewTablet language={language}/></DeviceFrame><DeviceFrame deviceType="mobile" screenWidth={9} screenHeight={19.5} screenRadius={22} screenInset={7} bezelWidth={7} orientation="portrait" label={p.mobile} className="aims-stage-mobile"><DashboardPreviewMobile language={language}/></DeviceFrame></div>}
