import {CheckCheck,Mail,MailOpen,Plus,ShieldCheck,UserCog} from 'lucide-react';
import {useState,type FormEvent} from 'react';
import {Badge,Button,Field,SelectField,TextAreaField} from '../components/ui';
import {DataTable,type DataColumn} from '../components/DataTable';
import {ConfirmDialog,Dialog,MutationFeedback,OfflineGate,PageHeader} from '../components/WorkflowUi';
import {rolePermissions,type Permission} from '../auth/permissions';
import {useApp} from '../context/AppContext';
import type {ActivityRecord,RoleRecord,SystemUser} from '../data/contracts';
import type {Notification} from '../domain/types';
import {useMockSnapshot,useRepository} from '../data/repositoryContext';

export function NotificationsPage(){
  const {language}=useApp(),nl=language==='nl',snapshot=useMockSnapshot(),repository=useRepository();
  const columns:DataColumn<Notification>[]=[{id:'title',label:nl?'Melding':'Notification',render:item=><strong>{item.title}</strong>,text:item=>item.title},{id:'message',label:nl?'Bericht':'Message',render:item=>item.message,text:item=>item.message},{id:'category',label:nl?'Categorie':'Category',render:item=><Badge tone={item.category}>{item.category}</Badge>,text:item=>item.category},{id:'time',label:nl?'Ontvangen':'Received',render:item=>item.time,text:item=>item.time},{id:'state',label:nl?'Status':'State',render:item=><Badge tone={item.read?'success':'danger'}>{item.read?(nl?'Gelezen':'Read'):(nl?'Ongelezen':'Unread')}</Badge>,text:item=>item.read?(nl?'Gelezen':'Read'):(nl?'Ongelezen':'Unread')},{id:'actions',label:nl?'Acties':'Actions',render:item=><Button variant="secondary" onClick={event=>{event.stopPropagation();void repository.execute({action:item.read?'notification.unread':'notification.read',entityId:item.id})}}>{item.read?<Mail/>:<MailOpen/>}{item.read?(nl?'Markeer als ongelezen':'Mark as unread'):(nl?'Markeer als gelezen':'Mark as read')}</Button>,text:()=>''}];
  return <OfflineGate><div className="page"><PageHeader title={nl?'Meldingencentrum':'Notification center'} description={nl?'Rolgebonden herinneringen, operationele aandacht en voorkeuren.':'Role-aware reminders, operational attention and preferences.'} actions={<Button onClick={()=>repository.execute({action:'notification.readAll'})}><CheckCheck/>{nl?'Alles gelezen':'Mark all read'}</Button>}/><section className="card data-card"><DataTable id="notifications" rows={snapshot.notifications} columns={columns} rowKey={item=>item.id} searchPlaceholder={nl?'Zoek meldingen…':'Search notifications…'} emptyTitle={nl?'Geen meldingen':'No notifications'} emptyDescription={nl?'Nieuwe operationele meldingen verschijnen hier.':'New operational notifications appear here.'} onRowClick={item=>repository.execute({action:'notification.read',entityId:item.id})}/></section><section className="card"><h2>{nl?'Meldingsvoorkeuren':'Notification preferences'}</h2>{['Overdue returns','Low stock','Maintenance due','Audit assignments'].map(label=><label className="switch-row" key={label}><span>{label}</span><input type="checkbox" defaultChecked/></label>)}</section></div></OfflineGate>;
}

export function UsersPage(){
  const {language}=useApp(),nl=language==='nl',snapshot=useMockSnapshot(),repository=useRepository();
  const [selected,setSelected]=useState<SystemUser|null>(null),[open,setOpen]=useState(false),[confirm,setConfirm]=useState(false);
  const [feedback,setFeedback]=useState<{status:'idle'|'loading'|'success'|'error';message:string}>({status:'idle',message:''});
  const columns:DataColumn<SystemUser>[]=[{id:'name',label:nl?'Gebruiker':'User',render:item=><span className="user-name-cell">{item.photo?<img src={item.photo} alt=""/>:<span aria-hidden="true">{item.name.split(/\s+/).map(part=>part[0]).slice(0,2).join('')}</span>}<strong>{item.name}</strong></span>,text:item=>item.name,sortable:true},{id:'email',label:'E-mail',render:item=>item.email,text:item=>item.email},{id:'role',label:nl?'Rol':'Role',render:item=>item.role,text:item=>item.role},{id:'department',label:nl?'Afdeling':'Department',render:item=>item.department,text:item=>item.department},{id:'login',label:nl?'Laatste aanmelding':'Last login',render:item=>item.lastLogin||'—',text:item=>item.lastLogin},{id:'status',label:'Status',render:item=><Badge tone={item.status==='Active'?'success':'neutral'}>{item.status}</Badge>,text:item=>item.status}];
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),photo=data.get('photo');let photoValue=selected?.photo;if(photo instanceof File&&photo.size)photoValue=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(photo)});data.delete('photo');const values={...Object.fromEntries(data.entries()),photo:photoValue};const result=await repository.execute({action:selected?'user.edit':'user.create',entityId:selected?.id,values});setFeedback({status:result.ok?'success':'error',message:result.message});if(result.ok)setOpen(false)}
  return <OfflineGate><div className="page"><PageHeader title={nl?'Gebruikers':'Users'} description={nl?'Accounts, rollen, afdelingen en activatiestatus.':'Accounts, roles, departments and activation status.'} actions={<Button onClick={()=>{setSelected(null);setOpen(true)}}><Plus/>{nl?'Gebruiker toevoegen':'Add user'}</Button>}/><section className="card data-card"><DataTable id="users" rows={snapshot.users} columns={columns} rowKey={item=>item.id} searchPlaceholder={nl?'Zoek gebruikers…':'Search users…'} emptyTitle={nl?'Geen gebruikers':'No users'} emptyDescription={nl?'Voeg een geautoriseerde gebruiker toe.':'Add an authorized user.'} onRowClick={item=>{setSelected(item);setOpen(true)}}/></section><Dialog open={open} title={selected?(nl?'Gebruiker bewerken':'Edit user'):(nl?'Gebruiker toevoegen':'Add user')} onClose={()=>setOpen(false)}><form className="workflow-form" onSubmit={save}><div className="user-photo-field wide">{selected?.photo?<img src={selected.photo} alt={selected.name}/>:<span aria-hidden="true">{selected?selected.name.split(/\s+/).map(part=>part[0]).slice(0,2).join(''):'+'}</span>}<Field name="photo" type="file" accept="image/png,image/jpeg,image/webp" label={nl?'Profielfoto uploaden':'Upload profile photo'}/></div><Field name="name" label={nl?'Naam':'Name'} defaultValue={selected?.name} required/><Field name="email" type="email" label="E-mail" defaultValue={selected?.email} required/><SelectField name="role" label={nl?'Rol':'Role'} defaultValue={selected?.role}>{snapshot.roles.map(role=><option key={role.id}>{role.name}</option>)}</SelectField><Field name="department" label={nl?'Afdeling':'Department'} defaultValue={selected?.department} required/><div className="wide"><MutationFeedback {...feedback}/><div className="actions user-edit-actions"><Button type="submit"><UserCog/>{nl?'Opslaan':'Save'}</Button>{selected&&<Button type="button" className={selected.status==='Active'?'user-danger-action':''} variant={selected.status==='Active'?'danger':'secondary'} onClick={()=>setConfirm(true)}>{selected.status==='Active'?(nl?'Deactiveren':'Deactivate'):(nl?'Activeren':'Activate')}</Button>}</div></div></form></Dialog><ConfirmDialog open={confirm} title={nl?'Accountstatus wijzigen':'Change account status'} description={nl?'De gebruiker behoudt historische activiteiten, maar toegang wordt aangepast.':'Historical activity remains, but access is changed.'} confirmLabel={nl?'Bevestigen':'Confirm'} danger={selected?.status==='Active'} onClose={()=>setConfirm(false)} onConfirm={async()=>{if(selected)await repository.execute({action:selected.status==='Active'?'user.deactivate':'user.activate',entityId:selected.id})}}/></div></OfflineGate>;
}

export function RolesPage(){
  const {language}=useApp(),nl=language==='nl',snapshot=useMockSnapshot(),repository=useRepository();
  const [open,setOpen]=useState(false),[selected,setSelected]=useState<RoleRecord|null>(null);
  const permissions=[...new Set(Object.values(rolePermissions).flat())] as Permission[];
  const columns:DataColumn<RoleRecord>[]=[{id:'name',label:nl?'Rol':'Role',render:item=><strong>{item.name}</strong>,text:item=>item.name},{id:'description',label:nl?'Beschrijving':'Description',render:item=>item.description,text:item=>item.description},{id:'permissions',label:nl?'Rechten':'Permissions',render:item=>item.permissions.length,text:item=>item.permissions.length},{id:'type',label:'Type',render:item=><Badge tone={item.system?'info':'neutral'}>{item.system?(nl?'Systeem':'System'):(nl?'Aangepast':'Custom')}</Badge>,text:item=>String(item.system)}];
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),values={name:data.get('name'),description:data.get('description'),permissions:data.getAll('permissions')};await repository.execute({action:selected?'role.edit':'role.create',entityId:selected?.id,values});setOpen(false)}
  return <OfflineGate><div className="page"><PageHeader title={nl?'Rollen en rechten':'Roles and permissions'} description={nl?'Capaciteiten, functieverdeling en goedkeuringsrechten.':'Capabilities, segregation of duties and approval permissions.'} actions={<Button onClick={()=>{setSelected(null);setOpen(true)}}><Plus/>{nl?'Rol maken':'Create role'}</Button>}/><section className="card data-card permission-matrix"><DataTable id="roles" rows={snapshot.roles} columns={columns} rowKey={item=>item.id} searchPlaceholder={nl?'Zoek rollen…':'Search roles…'} emptyTitle={nl?'Geen rollen':'No roles'} emptyDescription={nl?'Maak een aangepaste rol.':'Create a custom role.'} onRowClick={item=>{setSelected(item);setOpen(true)}}/></section><Dialog open={open} title={selected?(nl?'Rol bewerken':'Edit role'):(nl?'Rol maken':'Create role')} description={selected?.system?(nl?'Systeemrollen zijn alleen-lezen.':'System roles are read-only.'):undefined} onClose={()=>setOpen(false)}><form className="workflow-form" onSubmit={save}><Field name="name" label={nl?'Rolnaam':'Role name'} defaultValue={selected?.name} required disabled={selected?.system}/><TextAreaField name="description" label={nl?'Beschrijving':'Description'} defaultValue={selected?.description} disabled={selected?.system}/><fieldset className="permission-grid wide" disabled={selected?.system}><legend>{nl?'Rechtenmatrix':'Permission matrix'}</legend>{permissions.map(permission=><label key={permission}><input name="permissions" type="checkbox" value={permission} defaultChecked={selected?.permissions.includes(permission)}/>{permission}</label>)}</fieldset><Button type="submit" disabled={selected?.system}><ShieldCheck/>{nl?'Rol opslaan':'Save role'}</Button></form></Dialog></div></OfflineGate>;
}

export function ActivityPage(){
  const {language}=useApp(),nl=language==='nl',snapshot=useMockSnapshot();
  const columns:DataColumn<ActivityRecord>[]=[{id:'time',label:nl?'Datum en tijd':'Date and time',render:item=>item.at,text:item=>item.at,sortable:true},{id:'user',label:nl?'Gebruiker':'User',render:item=>item.user,text:item=>item.user},{id:'action',label:nl?'Actie':'Action',render:item=><strong>{item.action}</strong>,text:item=>item.action},{id:'entity',label:nl?'Record':'Record',render:item=>`${item.entityType} · ${item.entityId}`,text:item=>item.entityId},{id:'detail',label:nl?'Details':'Detail',render:item=>item.detail,text:item=>item.detail},{id:'result',label:nl?'Resultaat':'Result',render:item=><Badge tone={item.result==='Success'?'success':'danger'}>{item.result}</Badge>,text:item=>item.result}];
  return <OfflineGate><div className="page"><PageHeader title={nl?'Activiteitenlogboek':'Activity logs'} description={nl?'Onveranderlijke, doorzoekbare historie van belangrijke mockacties.':'Immutable, searchable history of important mock actions.'}/><section className="card data-card"><DataTable id="activity" rows={snapshot.activity} columns={columns} rowKey={item=>item.id} searchPlaceholder={nl?'Zoek activiteiten…':'Search activity…'} emptyTitle={nl?'Nog geen activiteiten':'No activity yet'} emptyDescription={nl?'Uitgevoerde mockacties verschijnen hier.':'Completed mock actions appear here.'}/></section></div></OfflineGate>;
}
