import {Bot,Bookmark,Clock3,Send,Settings2,Sparkles} from 'lucide-react';
import {useState} from 'react';
import {Link,useLocation,useParams} from 'react-router-dom';
import {Button,Card} from '../components/ui';
import {rolePermissions} from '../auth/permissions';
import {useApp} from '../context/AppContext';
import {useMockSnapshot} from '../data/repositoryContext';
import {DeterministicMockAiProvider,type AiAssistantResponse} from '../domain/wave8';

const provider=new DeterministicMockAiProvider();
const prompts={en:['Which assets are currently available?','Which borrowed items are overdue?','Which stock items are below reorder level?','Which repairs are waiting for approval?','Explain why I cannot access this record.'],nl:['Welke middelen zijn beschikbaar?','Welke leenitems zijn te laat?','Welke artikelen hebben lage voorraad?','Welke reparaties wachten op goedkeuring?','Leg uit waarom ik geen toegang heb.']};

export default function Assistant(){
  const app=useApp(),nl=app.language==='nl',snapshot=useMockSnapshot(),location=useLocation(),params=useParams(),[query,setQuery]=useState('');
  const [messages,setMessages]=useState<{who:'bot'|'you';text:string;response?:AiAssistantResponse}[]>([{who:'bot',text:nl?'Stel een geautoriseerde inventarisvraag. Ik kan geen gegevens wijzigen.':'Ask an authorized inventory question. I cannot change data.'}]);
  const section=location.pathname.includes('/history')?'history':location.pathname.includes('/saved')?'saved':location.pathname.includes('/settings')?'settings':params.conversationId?'detail':'chat';
  async function send(){const value=query.trim();if(!value)return;const response=await provider.query({query:value,language:app.language,permissions:app.user?rolePermissions[app.user.role]:[],snapshot});setMessages(current=>[...current,{who:'you',text:value},{who:'bot',text:response.answer,response}]);setQuery('')}
  if(section!=='chat')return <div className="page"><header className="page-title"><div><h1>{section==='history'?(nl?'Gesprekshistorie':'Conversation history'):section==='saved'?(nl?'Opgeslagen resultaten':'Saved results'):section==='settings'?(nl?'Assistentinstellingen':'Assistant settings'):(nl?'Gespreksdetail':'Conversation detail')}</h1><p>{nl?'Lokale, gesimuleerde en alleen-lezen AI-werkruimte.':'Local, simulated, read-only AI workspace.'}</p></div></header><Card><div className="state"><Bot/><h2>{nl?'Mockprovider actief':'Mock provider active'}</h2><p>{section==='detail'?`${nl?'Gesprek':'Conversation'} ${params.conversationId}`:nl?'Er zijn nog geen opgeslagen records in deze browsersessie.':'There are no saved records in this browser session yet.'}</p><Link className="btn primary" to="/assistant">{nl?'Assistent openen':'Open assistant'}</Link></div></Card></div>;
  return <div className="page assistant-page"><header className="page-title"><div><h1>{nl?'AI-inventarisassistent':'AI inventory assistant'}</h1><p>{nl?'Bevoegdheidsgebonden antwoorden uit de lokale mockmomentopname.':'Permission-filtered answers from the local mock snapshot.'}</p></div><div className="actions"><Link className="btn secondary" to="/assistant/history"><Clock3/>{nl?'Historie':'History'}</Link><Link className="btn secondary" to="/assistant/saved"><Bookmark/>{nl?'Opgeslagen':'Saved'}</Link><Link className="btn secondary" to="/assistant/settings"><Settings2/>{nl?'Instellingen':'Settings'}</Link></div></header><div className="notice warning"><strong>{nl?'Mock AI-provider · alleen lezen':'Mock AI provider · read only'}</strong><span> · {nl?'Geen externe AI-verbinding. Antwoorden kunnen gesimuleerd zijn en vereisen menselijke controle.':'No external AI connection. Answers may be simulated and require human review.'}</span></div><Card className="assistant-card"><div className="chat" aria-live="polite">{messages.map((message,index)=><div key={index} className={`message ${message.who}`}><span>{message.who==='bot'?<Bot/>:app.user?.initials}</span><p>{message.text}{message.response?.citations.length?<><br/><small>{nl?'Bronrecords':'Source records'}: {message.response.citations.map(item=>item.reference).join(', ')}</small></>:null}{message.response?.workflow&&<><br/><Link to={message.response.workflow}>{nl?'Workflow openen':'Open workflow'} →</Link></>}</p></div>)}</div><div className="suggestions">{prompts[app.language].slice(0,3).map(prompt=><button key={prompt} onClick={()=>setQuery(prompt)}><Sparkles/>{prompt}</button>)}</div><form onSubmit={event=>{event.preventDefault();void send()}}><label className="sr-only" htmlFor="assistant-query">{nl?'Vraag':'Question'}</label><input id="assistant-query" value={query} onChange={event=>setQuery(event.target.value)} placeholder={nl?'Vraag naar geautoriseerde mockgegevens…':'Ask about authorized mock data…'}/><Button aria-label={nl?'Versturen':'Send'}><Send/></Button></form><small>{nl?'Scope: uw effectieve rol · momentopname: huidige mockrepository · mutaties: geblokkeerd':'Scope: your effective role · snapshot: current mock repository · mutations: blocked'}</small></Card></div>;
}
