import {ClipboardCheck,Plus,QrCode} from 'lucide-react';
import {useState,type FormEvent} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {Badge,Button,Field,SelectField,TextAreaField} from '../components/ui';
import {DataTable,type DataColumn} from '../components/DataTable';
import {Dialog,MutationFeedback,OfflineGate,PageHeader} from '../components/WorkflowUi';
import {useApp} from '../context/AppContext';
import type {Audit} from '../domain/types';
import {useMockSnapshot,useRepository} from '../data/repositoryContext';

const outcomes=['Verified','Missing','Damaged','Wrong location','Wrong assigned user','Needs repair','Needs maintenance','Data incorrect','Not accessible'];
export default function AuditsPage(){
  const {language}=useApp(),nl=language==='nl',snapshot=useMockSnapshot(),repository=useRepository(),params=useParams(),navigate=useNavigate();
  const routeId=params.auditId||params.id;
  const [selected,setSelected]=useState<Audit|null>(()=>snapshot.audits.find(item=>item.id===routeId)||null),[create,setCreate]=useState(location.pathname.endsWith('/new')),[report,setReport]=useState(location.pathname.endsWith('/report'));
  const [feedback,setFeedback]=useState<{status:'idle'|'loading'|'success'|'error';message:string}>({status:'idle',message:''});
  const columns:DataColumn<Audit>[]=[
    {id:'reference',label:nl?'Controle':'Audit',render:item=><strong>{item.reference}</strong>,text:item=>item.reference,sortable:true},
    {id:'name',label:nl?'Naam':'Name',render:item=>item.name,text:item=>item.name},
    {id:'scope',label:nl?'Bereik':'Scope',render:item=>item.scope,text:item=>item.scope},
    {id:'assignee',label:nl?'Auditor':'Auditor',render:item=>item.assignee,text:item=>item.assignee},
    {id:'deadline',label:nl?'Deadline':'Deadline',render:item=>item.deadline,text:item=>item.deadline,sortable:true},
    {id:'progress',label:nl?'Voortgang':'Progress',render:item=>`${item.progress}%`,text:item=>item.progress,sortable:true},
    {id:'issues',label:nl?'Afwijkingen':'Discrepancies',render:item=>item.discrepancies,text:item=>item.discrepancies},
    {id:'status',label:'Status',render:item=><Badge tone={item.status==='Completed'?'success':'info'}>{item.status}</Badge>,text:item=>item.status}
  ];
  async function generate(event:FormEvent<HTMLFormElement>){event.preventDefault();const values:Record<string,unknown>=Object.fromEntries(new FormData(event.currentTarget).entries());if(values.percentage)values.count=Math.max(1,Math.round(snapshot.assets.length*Number(values.percentage)/100));const result=await repository.execute({action:'audit.generate',values});setFeedback({status:result.ok?'success':'error',message:result.message});if(result.ok){setCreate(false);setSelected(snapshot.audits.find(item=>item.id===result.entityId)||null);navigate(`/audits/${result.entityId}`)}}
  async function record(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const values=Object.fromEntries(new FormData(event.currentTarget).entries());const discrepancy=values.outcome!=='Verified';const result=await repository.execute({action:discrepancy?'audit.discrepancy':'audit.verify',entityId:selected.id,values});setFeedback({status:result.ok?'success':'error',message:result.message})}
  const frozen=selected?.frozenItemIds?.map(id=>snapshot.assets.find(asset=>asset.id===id)).filter(Boolean)||[];
  return <OfflineGate><div className="page"><PageHeader title={nl?'Inventariscontroles':'Inventory audits'} description={nl?'Voorbereiding, vaste steekproeven, QR-verificatie, resultaten en correctieve acties.':'Preparation, frozen samples, QR verification, results and corrective actions.'} actions={<Button onClick={()=>setCreate(true)}><Plus/>{nl?'Controle voorbereiden':'Prepare audit'}</Button>}/><section className="card data-card"><DataTable id="audits" rows={snapshot.audits} columns={columns} rowKey={item=>item.id} searchPlaceholder={nl?'Zoek controles…':'Search audits…'} emptyTitle={nl?'Geen controles':'No audits'} emptyDescription={nl?'Bereid de eerste inventariscontrole voor.':'Prepare the first inventory audit.'} onRowClick={setSelected}/></section>
    <Dialog open={create} title={nl?'Controle voorbereiden':'Prepare audit'} description={nl?'De gegenereerde lijst wordt na aanmaak bevroren.':'The generated item list is frozen after creation.'} onClose={()=>{setCreate(false);if(location.pathname.endsWith('/new'))navigate('/audits')}}><form className="workflow-form" onSubmit={generate}><Field name="name" label={nl?'Naam':'Name'} required/><SelectField name="selectionMode" label={nl?'Selectietype':'Selection type'}><option>Mixed</option><option>Serialized items</option><option>Quantity-based items</option></SelectField><Field name="count" type="number" min="1" label={nl?'Aantal':'Item count'} defaultValue="5"/><Field name="percentage" type="number" min="1" max="100" label={nl?'Percentage (optioneel)':'Percentage (optional)'}/><SelectField name="category" label={nl?'Categorie':'Category'}><option value="">{nl?'Alle categorieën':'All categories'}</option>{[...new Set(snapshot.assets.map(asset=>asset.category))].map(value=><option key={value}>{value}</option>)}</SelectField><SelectField name="location" label={nl?'Locatie':'Location'}><option value="">{nl?'Alle locaties':'All locations'}</option>{[...new Set(snapshot.assets.map(asset=>asset.location))].map(value=><option key={value}>{value}</option>)}</SelectField><SelectField name="department" label={nl?'Afdeling':'Department'}><option value="">{nl?'Alle afdelingen':'All departments'}</option>{[...new Set(snapshot.assets.map(asset=>asset.department))].map(value=><option key={value}>{value}</option>)}</SelectField><Field name="assignee" label={nl?'Toegewezen auditors':'Assigned auditors'} required/><Field name="deadline" type="date" label={nl?'Deadline':'Deadline'} required/><label className="switch-row wide"><span>{nl?'Recent gecontroleerde items uitsluiten':'Exclude recently audited items'}</span><input name="excludeRecent" type="checkbox" defaultChecked/></label><div className="wide"><MutationFeedback {...feedback}/><Button type="submit"><ClipboardCheck/>{nl?'Vaste lijst genereren':'Generate frozen list'}</Button></div></form></Dialog>
    <Dialog open={!!selected&&!report} title={selected?.reference||''} description={selected?.scope} onClose={()=>{setSelected(null);if(params.id)navigate('/audits')}}>{selected&&<><div className="status-summary"><section className="card"><b>{selected.progress}%</b><small>{nl?'Voortgang':'Progress'}</small></section><section className="card"><b>{selected.verified}</b><small>{nl?'Geverifieerd':'Verified'}</small></section><section className="card"><b>{selected.discrepancies}</b><small>{nl?'Afwijkingen':'Discrepancies'}</small></section></div><div className="audit-items">{frozen.length?frozen.map(asset=><div key={asset!.id}><QrCode/><span><b>{asset!.code}</b><small>{asset!.name}</small></span></div>):<p>{nl?'Legacycontrole zonder bevroren mocklijst.':'Legacy audit without a frozen mock list.'}</p>}</div><form className="workflow-form" onSubmit={record}><Field name="scannedCode" label={nl?'Gescande QR-/KCS-code':'Scanned QR/KCS code'} required/><SelectField name="outcome" label={nl?'Resultaat':'Result'}>{outcomes.map(value=><option key={value}>{value}</option>)}</SelectField><TextAreaField name="notes" className="wide" label={nl?'Bewijs en notities':'Evidence and notes'}/><TextAreaField name="correctiveAction" className="wide" label={nl?'Correctieve actie':'Corrective action'}/><Button type="submit">{nl?'Resultaat vastleggen':'Record result'}</Button><Button type="button" variant="secondary" onClick={()=>setReport(true)}>{nl?'Rapportvoorbeeld':'Report preview'}</Button></form><MutationFeedback {...feedback}/></>}</Dialog>
    <Dialog open={report} title={nl?'Controlerapport':'Audit report'} description={selected?.reference} onClose={()=>setReport(false)}><div className="print-preview"><header><strong>AIMS Asset & Inventory Management System</strong><h2>{selected?.name}</h2></header><p>{selected?.scope}</p><p>{nl?'Auditor':'Auditor'}: {selected?.assignee}</p><p>{nl?'Voortgang':'Progress'}: {selected?.progress}% · {nl?'Afwijkingen':'Discrepancies'}: {selected?.discrepancies}</p><footer><span>{nl?'Officiële schoolgegevens nog niet geleverd':'Official school information not supplied'}</span><span>1 / 1</span></footer></div></Dialog>
  </div></OfflineGate>;
}
