import {ClipboardList,Printer,Save} from 'lucide-react';
import {useState,type FormEvent} from 'react';
import {Button,Field,SelectField,TextAreaField} from '../components/ui';
import {MutationFeedback,OfflineGate,PageHeader} from '../components/WorkflowUi';
import {useApp} from '../context/AppContext';
import {useRepository} from '../data/repositoryContext';

const forms=['Laptop registration','Printer service','Module / desktop','Smartboard'];
export default function ServiceFormsPage(){
  const {language}=useApp(),nl=language==='nl',repository=useRepository(),[form,setForm]=useState(forms[0]),[feedback,setFeedback]=useState<{status:'idle'|'loading'|'success'|'error';message:string}>({status:'idle',message:''});
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget).entries());const result=await repository.execute({action:'movement.create',values:{type:'Service form',asset:String(values.assetName),assetCode:String(values.code),quantity:1,from:'Registered location',to:'ICT records',reason:`${form}: ${values.notes}`}});setFeedback({status:result.ok?'success':'error',message:result.message})}
  return <OfflineGate><div className="page service-forms-page"><PageHeader title={nl?'Serviceformulieren':'Service forms'} description={nl?'Gestructureerde registratie voor laptops, printers, desktops, modules en smartboards.':'Structured registration for laptops, printers, desktops, modules and smartboards.'} actions={<Button variant="secondary" onClick={()=>window.print()}><Printer/>{nl?'Formulier afdrukken':'Print form'}</Button>}/><div className="subnav">{forms.map(value=><button key={value} className={form===value?'active':''} onClick={()=>setForm(value)}><ClipboardList/>{value}</button>)}</div><section className="card service-form-card"><header className="service-form-print-heading"><strong>AIMS Asset & Inventory Management System</strong><h2>{form}</h2></header><form className="workflow-form" onSubmit={submit}><Field name="code" label="KCS code" required/><Field name="assetName" label={nl?'Middelnaam':'Asset name'} required/><Field name="brand" label={nl?'Merk':'Brand'} required/><Field name="model" label="Model" required/>{form==='Laptop registration'&&<><Field name="processor" label="Processor"/><Field name="memory" label={nl?'Geheugen':'Memory'}/><Field name="storage" label={nl?'Opslag':'Storage'}/></>}{form==='Printer service'&&<><SelectField name="technology" label={nl?'Printertechnologie':'Printer technology'}><option>Laser</option><option>Inkjet</option></SelectField><Field name="counter" type="number" label={nl?'Paginateller':'Page counter'}/></>}{form==='Module / desktop'&&<Field name="moduleSerial" label={nl?'Module-/desktopserienummer':'Module / desktop serial'}/>} {form==='Smartboard'&&<Field name="boardSerial" label={nl?'Bordserienummer':'Board serial'}/>}<TextAreaField name="notes" className="wide" label={nl?'Technische notities':'Technical notes'}/><div className="wide service-form-actions"><MutationFeedback {...feedback}/><div className="actions"><Button type="submit"><Save/>{nl?'Serviceformulier opslaan':'Save service form'}</Button><Button type="button" variant="secondary" onClick={()=>window.print()}><Printer/>{nl?'Afdrukken':'Print'}</Button></div></div></form></section></div></OfflineGate>;
}
