import type {LegalSection} from '../types/legal.types';

const s=(number:string,id:string,title:string,paragraphs:string[],bulletPoints?:string[],table?:LegalSection['table']):LegalSection=>({number,id,title,paragraphs,bulletPoints,table});

export const termsSectionsNl:LegalSection[]=[
s('1','introduction','Inleiding en aanvaarding',['Het AIMS Asset & Inventory Management System (het Systeem) is eigendom van en wordt beheerd door St. Kangoeroe Community School (KCS), hoofdzakelijk voor bevoegd schoolpersoneel. Gebruikers moeten deze Algemene voorwaarden lezen en naleven. Door aan te melden, toegang te krijgen of het Systeem te gebruiken, stemt de gebruiker met deze voorwaarden in. Wie niet instemt, mag het Systeem niet gebruiken.']),
s('2','purpose','Doel van het Systeem',['Het Systeem ondersteunt registratie van schoolmiddelen; toewijzing en uitlening; beheer van middelen voor ongeveer 200 leerkrachten en bevoegde medewerkers; locatie- en verantwoordelijkheidsregistratie; retouren en overdrachten; verlies, diefstal, schade, reparatie en onderhoud; serviceverzoeken; inventariscontroles; bevoegde rapporten; QR-codes; afschrijving en verwijdering; verantwoording en operationele controle.','Het Systeem is geen algemeen leerling-, salaris- of volledig HR-systeem en vervangt geen financieel, juridisch, verzekerings- of professioneel auditadvies.']),
s('3','authorized-users','Bevoegde gebruikers',['Bevoegde gebruikers kunnen ICT-medewerkers, systeembeheerders, inventarismedewerkers, schoolmanagement, bevoegde leerkrachten en medewerkers, goedgekeurde auditors en andere goedgekeurde personen zijn. Toegang is gebaseerd op toegewezen rollen en verantwoordelijkheden.']),
s('4','accounts','Gebruikersaccounts en toegangsbeveiliging',['Gebruikers moeten juiste gegevens verstrekken, wachtwoorden en verificatiegegevens beschermen, accounts nooit delen, uitsluitend hun bevoegde account gebruiken, verdachte activiteit direct melden, op gedeelde apparaten afmelden, rolrechten volgen en beveiliging of onbevoegde gegevens nooit omzeilen.','KCS kan accounts opschorten of uitschakelen, inloggegevens herstellen, rechten beperken, verdachte activiteit onderzoeken en toegang beëindigen wanneer de bevoegdheid eindigt.']),
s('5','acceptable-use','Aanvaardbaar gebruik',['Het Systeem mag uitsluitend worden gebruikt voor rechtmatige KCS-activiteiten rond inventaris, middelen, ondersteuning, administratie en audits.'],['Onbevoegde toegang of wijziging','Vervalsen, verwijderen of verbergen van gegevens','Fictieve toewijzingen of omzeilen van goedkeuringen','Openbaar maken van vertrouwelijke informatie','Schadelijke uploads, malware of virussen','Persoonlijk commercieel gebruik of onbevoegde exports','Verstoring, pogingen wachtwoorden te achterhalen of misbruik van QR-codes, rapporten of auditgegevens']),
s('6','assignment-borrowing','Toewijzing en uitlening van middelen',['Alleen bevoegde leerkrachten en medewerkers mogen middelen ontvangen of lenen en elke toewijzing moet worden vastgelegd. De toestand kan verificatie vereisen en leners moeten zorgvuldig handelen. Middelen mogen niet zonder toestemming worden overgedragen; retour, verlies, diefstal en schade moeten snel worden gemeld. KCS kan middelen inspecteren, terughalen, intrekken of opnieuw toewijzen. Een systeemregistratie vervangt geen afzonderlijke ondertekende leen- of verantwoordelijkheidsovereenkomst.']),
s('7','accuracy','Juistheid van informatie',['Gebruikers moeten juiste en volledige informatie invoeren. Correcties moeten de bevoegde procedure volgen, auditgeschiedenis behouden, eerdere handelingen niet verbergen en waar nodig een reden bevatten. KCS mag aantoonbaar onjuiste informatie corrigeren met behoud van verantwoording.']),
s('8','identifiers','QR-codes en middelidentificatie',['KCS QR- en middelcodes zijn officiële identificatiemiddelen. Onbevoegd verwijderen, vervangen, dupliceren, kopiëren, manipuleren of misbruiken is verboden. Dubbele identificaties mogen niet worden aangemaakt. QR-gegevens blijven onder rolrechten vallen en scans mogen geen onnodige persoonsgegevens tonen.']),
s('9','ai','AI-ondersteunde functies',['AI-functies kunnen door OpenAI worden geleverd. AI-uitvoer is ondersteunend, kan onjuist, onvolledig of ongeschikt zijn en is niet automatisch gezaghebbend. Gebruikers moeten de uitvoer controleren. AI mag geen definitieve disciplinaire, arbeidsrechtelijke, verwijderings-, financiële, audit- of juridische beslissingen nemen. Voer geen onnodige vertrouwelijke, gevoelige of persoonlijke informatie in. Toegang volgt rolrechten en KCS kan AI-functies uitschakelen of wijzigen.']),
s('10','exports','Rapporten, downloads en exports',['Rapporten en exports kunnen vertrouwelijke of persoonlijke informatie bevatten en zijn alleen toegestaan voor bevoegde doeleinden. Bestanden moeten veilig worden opgeslagen en niet aan onbevoegden worden verspreid; exportactiviteit kan worden gelogd. Tijdelijke exports moeten na gebruik veilig worden verwijderd, uiterlijk binnen 30 dagen, tenzij zij een goedgekeurd officieel document worden.']),
s('11','monitoring','Monitoring en auditlogboeken',['Voor rechtmatige beveiliging, ondersteuning, verantwoording, bedrijfsvoering en audits kunnen logboeken accounttoegang, geslaagde en mislukte aanmeldingen, aanmaak en wijzigingen, rol- en rechtenwijzigingen, toewijzingen, goedkeuringen, rapporten, exports, beheerhandelingen en beveiligingsgebeurtenissen vastleggen.']),
s('12','intellectual-property','Intellectueel eigendom',['Het Systeem, de interface, documentatie, huisstijl, werkstromen, databasestructuur en inhoud zijn eigendom van KCS of bevoegde licentiegevers. Gebruikers krijgen een beperkt recht om het Systeem voor bevoegde KCS-activiteiten te gebruiken. Onbevoegd kopiëren, doorverkopen, verspreiden, reverse-engineeren of commercieel exploiteren is verboden.','© 2026 St. Kangoeroe Community School. Alle rechten voorbehouden. Ontworpen en ontwikkeld door Shaquil Alienda.']),
s('13','third-parties','Diensten van derden',['Het Systeem kan Firebase Authentication, Cloud Firestore, Firebase Storage, Firebase Hosting, Firebase Cloud Functions, waar ingeschakeld Firebase Cloud Messaging, en OpenAI gebruiken. Beschikbaarheid kan van deze leveranciers afhangen; zij kunnen beperkte technische of applicatiegegevens verwerken volgens hun overeenkomsten en privacypraktijken.']),
s('14','availability','Beschikbaarheid en onderhoud',['KCS streeft naar beschikbaarheid maar garandeert geen ononderbroken toegang. Onderbrekingen kunnen ontstaan door onderhoud, upgrades, beveiligingsmaatregelen, internet- of hostingstoringen, storingen bij derden of technische problemen. KCS kan functies wijzigen, opschorten of beëindigen wanneer dat operationeel nodig is.']),
s('15','termination','Opschorting en beëindiging',['KCS kan toegang opschorten of beëindigen wanneer een gebruiker de organisatie verlaat, van rol verandert, geen toegang meer nodig heeft, deze voorwaarden schendt, een beveiligingsrisico vormt, informatie misbruikt of bevoegde instructies niet opvolgt. Historische auditinformatie kan na deactivering behouden blijven.']),
s('16','disclaimer','Disclaimer en beperking',['Het Systeem ondersteunt inventarisbeheer; gebruikers moeten kritieke informatie controleren. Het vervangt geen boekhoudkundig, juridisch, verzekerings-, financieel of professioneel auditadvies. Voor zover wettelijk toegestaan is KCS niet verantwoordelijk voor verliezen door onbevoegd gebruik, gedeelde inloggegevens, onjuiste gebruikersinvoer, externe internetstoringen of gebeurtenissen buiten redelijke controle. Dit sluit geen aansprakelijkheid uit waar dat onrechtmatig zou zijn.']),
s('17','changes','Wijzigingen van de voorwaarden',['KCS kan deze voorwaarden bijwerken. Materiële wijzigingen krijgen een nieuw versienummer en een bijgewerkte datum, kunnen in het Systeem worden meegedeeld en kunnen een nieuwe bevestiging vereisen.']),
s('18','governing','Toepasselijk kader',['Deze voorwaarden vallen onder de toepasselijke wetten en regels van Suriname en de bevoegde beleidsregels en procedures van KCS.']),
s('19','contact','Contactgegevens',['St. Kangoeroe Community School, Edmundstraat 3–5, Uitvlucht, Paramaribo, Suriname. Telefoon: +597 430870. Algemeen e-mailadres: administratie@kangoeroeschool.com. ICT, privacy en beveiliging: servicedesk@kangoeroeschool.com. Website: https://www.kangoeroecommunityschool.com. Facebook: Kangoeroe Community School.'])];

const retentionRowsNl=[['Actieve gebruikersaccounts','Bewaren zolang toegang bevoegd blijft.'],['Gedeactiveerde accounts','Twee jaar na deactivering bewaren.'],['Middelregistraties','Volledige levensduur plus vijf jaar na afschrijving of definitieve verwijdering.'],['Toewijzings- en leengeschiedenis','Levensduur van het middel plus vijf jaar.'],['Onderhouds- en reparatiegegevens','Levensduur van het middel plus vijf jaar.'],['Auditgegevens','Zeven jaar na afronding.'],['Beveiligings- en activiteitenlogboeken','Twaalf maanden.'],['Mislukte aanmeldingen','Zes maanden.'],['Tijdelijke exports','Na gebruik en uiterlijk binnen dertig dagen verwijderen, tenzij goedgekeurd als officieel document.']];
export const privacySectionsNl:LegalSection[]=[
s('1','responsible','Wie is verantwoordelijk',['St. Kangoeroe Community School is verantwoordelijk voor de verwerking in deze verklaring. KCS heeft momenteel geen afzonderlijke privacyfunctionaris aangesteld. Privacy- en beveiligingsverzoeken worden behandeld door de KCS ICT-afdeling via servicedesk@kangoeroeschool.com.']),
s('2','scope','Reikwijdte',['Deze verklaring geldt voor de webapp, mobiele app of geïnstalleerde PWA van het AIMS Asset & Inventory Management System, beheerinterfaces, ondersteunings- en beveiligingsprocessen, inventaris- en middelgegevens, bijbehorende rapporten en goedgekeurde exports.']),
s('3','people','Categorieën personen',['Het Systeem kan informatie verwerken over leerkrachten, bevoegde medewerkers, ICT-personeel, systeem- en inventarisbeheerders, management, goedgekeurde auditors, aangewezen ondersteuning en andere bevoegde gebruikers. Het beheert hoofdzakelijk middelen die aan ongeveer 200 leerkrachten en bevoegde medewerkers zijn toegewezen of uitgeleend.']),
s('4','information','Verzamelde informatie',['Gegevens van leerkrachten en medewerkers kunnen bestaan uit naam, waar nodig e-mail, telefoonnummer, rol, afdeling, accountstatus, transactiegegevens, toegewezen middelen, leen- en retourgeschiedenis, serviceverzoeken, onderhoud, goedkeuringen en auditgeschiedenis. E-mail wordt alleen opgeslagen wanneer nodig voor bevoegde accounts, authenticatie, service, communicatie of meldingen; een e-mailadres mag niet alleen worden verzameld omdat iemand een middel leent.','Personeelsnummers worden momenteel niet opgeslagen. Firebase of het Systeem kan een interne technische gebruikerscode maken, maar dit is geen officieel salaris- of personeelsnummer.','Het Systeem is niet bedoeld om standaard leerlinggegevens op te slaan. Leerlinggegevens zijn geen gewone categorie en mogen niet worden toegevoegd zonder formeel goedgekeurde toekomstige functie en beleidswijziging.','Middel- en transactiegegevens kunnen codes, QR-codes, serienummers, categorie, merk, model, toestand, locatie, toegewezen persoon, data, overdrachten, reparaties, verlies- en schaderapporten, afschrijving en bevoegde foto’s en documenten omvatten.','IP-adressen kunnen technisch worden verwerkt voor authenticatie, hosting, beveiliging, menselijke verificatie, audits, misbruikpreventie, probleemoplossing of incidentonderzoek. De app beweert niet altijd IP-adressen vast te leggen. Beperkte browser-, apparaat-, systeem-, appversie-, taal-, aanmeld- en foutgegevens kunnen worden gebruikt voor beveiliging, compatibiliteit, prestaties en ondersteuning.']),
s('5','purposes','Doeleinden van verwerking',['Informatie kan worden verwerkt om accounts te beheren, gebruikers te verifiëren, roltoegang af te dwingen, middelen en toewijzingen te beheren, lenen, retouren, overdrachten, reparaties en service vast te leggen, goedkeuringen en audits uit te voeren, verlies, diefstal, schade of misbruik te onderzoeken, rapporten te maken, het Systeem te beschermen, ondersteuning te bieden, bewaarplichten na te leven en stabiliteit te verbeteren.']),
s('6','minimization','Gegevensminimalisatie',['Alleen redelijkerwijs noodzakelijke informatie mag worden verzameld. Onnodige gevoelige of persoonlijke informatie mag niet worden ingevoerd; vrije tekst mag geen niet-relevante persoonsgegevens bevatten; QR-codes mogen geen onnodige persoonsgegevens tonen en toegang volgt het beginsel van minimale rechten.']),
s('7','ai-processing','AI-verwerking',['Bevoegde gebruikers kunnen OpenAI-functies gebruiken en ingevoerde gegevens kunnen voor verwerking worden verzonden. Dien geen onnodige vertrouwelijke, gevoelige of persoonlijke gegevens in. AI-uitvoer vereist menselijke controle en mag geen definitieve arbeids-, disciplinaire, juridische, financiële, audit- of verwijderingsbeslissingen nemen. Toegang volgt rolrechten en gebruik kan voor beveiliging en verantwoording worden gelogd.']),
s('8','basis','Organisatorische grondslag',['KCS verwerkt informatie waar nodig voor rechtmatig schoolbeheer, middelenbeheer, beveiliging, verantwoording, uitvoering van bevoegde taken, organisatorische verantwoordelijkheden en toepasselijke wettelijke of contractuele verplichtingen.']),
s('9','access','Toegang tot informatie',['Toegang kan uitsluitend worden gegeven aan bevoegd ICT-personeel, systeem- en inventarisbeheerders, management, goedgekeurde auditors en ondersteuning. Toegang is rolgebaseerd en volgt minimale rechten.']),
s('10','providers','Externe dienstverleners',['Firebase Authentication, Cloud Firestore, Firebase Storage, Firebase Hosting, Firebase Cloud Functions, waar ingeschakeld Firebase Cloud Messaging, en OpenAI kunnen technische of applicatiegegevens verwerken die nodig zijn voor hun diensten. KCS beweert niet dat alle gegevens uitsluitend in Suriname blijven.']),
s('11','security','Opslag en beveiliging',['Maatregelen kunnen bestaan uit authenticatie, rolgebaseerde autorisatie, Firestore- en Storage Rules, beveiligde verbindingen, auditlogboeken, accountdeactivering, minimale rechten, beperkte beheerderstoegang, monitoring, back-up- en herstelcontroles en incidentprocedures. Geen enkel systeem kan absolute beveiliging garanderen.']),
s('12','retention','Bewaartermijnen',['Actieve accounts moeten snel worden uitgeschakeld wanneer toegang niet meer nodig is. Gedeactiveerde accounts worden na twee jaar beoordeeld; onnodige profielgegevens kunnen daarna worden verwijderd of geanonimiseerd. Namen kunnen blijven waar verwijdering historische verantwoording schaadt. Incidentlogboeken kunnen tijdens onderzoek langer worden bewaard en officiële documenten volgen hun geldende termijn.'],undefined,{headers:['Type registratie','Bewaartermijn'],rows:retentionRowsNl}),
s('13','requests','Verzoeken van betrokkenen',['Bevoegde personen kunnen via servicedesk@kangoeroeschool.com inzage, correctie, uitleg over verwerking, accountbeoordeling, waar passend verwijdering of beperking, of onderzoek naar vermoed misbruik of onbevoegde toegang vragen. Identiteitscontrole kan nodig zijn. Verwijdering kan niet worden gegarandeerd wanneer gegevens nodig blijven voor middelenverantwoording, audits, transacties, beveiliging of wetgeving.']),
s('14','incidents','Melding van privacy- en beveiligingsincidenten',['Meldingen gaan eerst naar de KCS ICT-afdeling. Technische meldingen worden beoordeeld door de ICT Manager, Head of Planning and Coordinator of the ICT Department, systeembeheerder of een aangewezen ICT-medewerker. Ernstige incidenten rond persoonsgegevens, medewerkers of juridisch, financieel, reputatie- of groot organisatierisico worden aan de schooldirecteur gemeld. KCS heeft geen afzonderlijke privacyfunctionaris.','ICT Support – Kangoeroe School · servicedesk@kangoeroeschool.com · +597 430870']),
s('15','changes','Wijzigingen in de privacyverklaring',['KCS kan deze verklaring bijwerken. Elke versie toont versienummer, ingangsdatum en datum van laatste wijziging. Materiële wijzigingen kunnen in het Systeem worden gemeld en een bevestiging vereisen.']),
s('16','contact','Contactgegevens',['St. Kangoeroe Community School, Edmundstraat 3–5, Uitvlucht, Paramaribo, Suriname. Telefoon: +597 430870. Algemeen: administratie@kangoeroeschool.com. Privacy en beveiliging: servicedesk@kangoeroeschool.com. Website: https://www.kangoeroecommunityschool.com. Facebook: Kangoeroe Community School.'])];
