import type {LegalSection} from '../types/legal.types';
const s=(number:string,id:string,title:string,paragraphs:string[],bulletPoints?:string[],table?:LegalSection['table']):LegalSection=>({number,id,title,paragraphs,bulletPoints,table});
export type {LegalSection} from '../types/legal.types';

export const termsSections:LegalSection[]=[
s('1','introduction','Introduction and Acceptance',['The AIMS Asset & Inventory Management System (System) is owned and operated by St. Kangoeroe Community School (KCS) and is intended primarily for authorized school personnel. Users must read and comply with these Terms & Conditions. Signing in, accessing, or using the System constitutes agreement to these Terms. Anyone who does not agree must not use the System.']),
s('2','purpose','Purpose of the System',['The System supports registration of school-owned assets; assignment and lending; management of assets provided to approximately 200 teachers and authorized employees; location and responsibility tracking; returns and transfers; loss, theft, damage, repair and maintenance records; service requests; inventory audits; authorized reports; QR-code generation and scanning; write-off and disposal administration; accountability; and operational control.','The System is not a general student-information system, payroll system, complete human-resources system, or substitute for financial, legal, insurance, or professional audit advice.']),
s('3','authorized-users','Authorized Users',['Authorized users may include ICT personnel, system administrators, inventory personnel, school management, authorized teachers and employees, approved auditors, and other approved persons. Access is based on assigned roles and responsibilities.']),
s('4','accounts','User Accounts and Access Security',['Users must provide accurate information, protect passwords and authentication credentials, never share accounts, use only their authorized account, report suspicious activity immediately, sign out on shared devices, follow role permissions, and never bypass security or access unauthorized records.','KCS may suspend or disable accounts, reset credentials, restrict permissions, investigate suspicious activity, and terminate access when authorization ends.']),
s('5','acceptable-use','Acceptable Use',['The System may be used only for legitimate KCS inventory, asset, support, administrative, and audit activities.'],['Unauthorized access or alteration','Falsification, deletion, or concealment of records','Fictitious assignments or bypassing approvals','Disclosure of confidential information','Malicious uploads, malware, or viruses','Personal commercial use or unauthorized exports','Disruption, password-discovery attempts, QR-code misuse, report misuse, or audit-record misuse']),
s('6','assignment-borrowing','Asset Assignment and Borrowing',['Only authorized teachers and employees may receive or borrow assets, and each assignment must be recorded. Condition may require verification and borrowers must exercise reasonable care. Assets may not be transferred without authorization; returns, loss, theft, and damage must be reported promptly. KCS may inspect, recover, withdraw, or reassign assets. A System record does not replace a separate signed loan or responsibility agreement.']),
s('7','accuracy','Accuracy of Information',['Users must enter accurate and complete information. Corrections must follow authorization procedures, preserve audit history, avoid concealing previous actions, and include reasons where required. KCS may correct demonstrably inaccurate information while maintaining accountability.']),
s('8','identifiers','QR Codes and Asset Identifiers',['KCS QR codes and asset codes are official identifiers. Unauthorized removal, replacement, duplication, copying, manipulation, or misuse is prohibited. Duplicate identifiers must not be created. QR data remains subject to role permissions and scanning must not expose unnecessary personal information.']),
s('9','ai','AI-Assisted Functionality',['AI-assisted functionality may be powered by OpenAI. AI output is supportive, may be inaccurate, incomplete, or unsuitable, and is not automatically authoritative. Users must verify output. AI cannot make final disciplinary, employment, disposal, financial, audit, or legal decisions. Users must not enter unnecessary confidential, sensitive, or personal information. Access follows role permissions and KCS may disable or modify AI functionality.']),
s('10','exports','Reports, Downloads, and Exports',['Reports and exports may contain confidential or personal information and are permitted only for authorized purposes. Files must be stored securely, must not be distributed to unauthorized parties, and export activity may be logged. Temporary exports must be securely deleted after use and no later than 30 days unless they become approved official records.']),
s('11','monitoring','Monitoring and Audit Logs',['For legitimate security, support, accountability, operational, and audit purposes, logs may record account access, successful and failed logins, record creation and changes, role and permission changes, assignments, approvals, reports, exports, administrative actions, and security events.']),
s('12','intellectual-property','Intellectual Property',['The System, interface, documentation, branding, workflows, database structure, and content belong to KCS or authorized licensors. Users receive a limited right to use the System for authorized KCS activities. Unauthorized copying, resale, redistribution, reverse engineering, or commercial exploitation is prohibited.','© 2026 St. Kangoeroe Community School. All rights reserved. Designed and developed by Shaquil Alienda.']),
s('13','third-parties','Third-Party Services',['The System may use Firebase Authentication, Cloud Firestore, Firebase Storage, Firebase Hosting, Firebase Cloud Functions, Firebase Cloud Messaging where enabled, and OpenAI. Availability may depend on these providers, which may process limited technical or application information under their applicable agreements and privacy practices.']),
s('14','availability','Availability and Maintenance',['KCS aims to maintain availability but uninterrupted access is not guaranteed. Downtime may result from maintenance, upgrades, security action, internet or hosting failure, third-party outages, or technical problems. KCS may modify, suspend, or discontinue features where operationally necessary.']),
s('15','termination','Suspension and Termination',['KCS may suspend or terminate access when a user leaves the organization, changes role, no longer requires access, violates these Terms, poses a security risk, misuses information, or fails to comply with authorized instructions. Historical audit information may remain after deactivation.']),
s('16','disclaimer','Disclaimer and Limitation',['The System supports inventory administration and users must verify critical information. It does not replace accounting, legal, insurance, financial, or professional audit advice. Subject to applicable law, KCS is not responsible for losses caused by unauthorized use, shared credentials, inaccurate user input, external internet failures, or events outside reasonable control. Nothing excludes responsibility where exclusion would be unlawful.']),
s('17','changes','Changes to the Terms',['KCS may update these Terms. Material changes receive a new version number and updated date, may be communicated in the System, and may require renewed acknowledgement.']),
s('18','governing','Governing Framework',['These Terms are governed by applicable laws and regulations of Suriname and authorized KCS policies and procedures.']),
s('19','contact','Contact Information',['St. Kangoeroe Community School, Edmundstraat 3–5, Uitvlucht, Paramaribo, Suriname. Telephone: +597 430870. General email: administratie@kangoeroeschool.com. ICT, privacy, and security: servicedesk@kangoeroeschool.com. Website: https://www.kangoeroecommunityschool.com. Facebook: Kangoeroe Community School.'])];

export const retentionRows=[['Active user accounts','Retain while access remains authorized.'],['Deactivated accounts','Retain for two years after deactivation.'],['Asset records','Complete asset lifetime plus five years after disposal or permanent removal.'],['Assignment and loan history','Related asset lifetime plus five years.'],['Maintenance and repair records','Related asset lifetime plus five years.'],['Audit records','Seven years after completion.'],['Security and activity logs','Twelve months.'],['Failed-login logs','Six months.'],['Temporary exports','Delete after use and no later than thirty days unless approved as official records.']] as const;
export const privacySections:LegalSection[]=[
s('1','responsible','Who Is Responsible',['St. Kangoeroe Community School is responsible for the processing described in this Notice. KCS has not currently appointed a separate privacy officer. Privacy and security requests are handled by the KCS ICT Department at servicedesk@kangoeroeschool.com.']),
s('2','scope','Scope',['This Notice applies to the AIMS Asset & Inventory Management System web application, mobile application or installed PWA, administrative interfaces, support and security processes, inventory and asset records, related reports, and approved exports.']),
s('3','people','Categories of People',['The System may process information relating to teachers, authorized employees, ICT personnel, system administrators, inventory personnel, management, approved auditors, designated support personnel, and other authorized users. It primarily manages assets assigned or loaned to approximately 200 teachers and authorized employees.']),
s('4','information','Information Collected',['Teacher and employee information may include full name, email where required, telephone number, role, department, account status, transaction dates and times, assigned assets, loan and return history, service requests, maintenance, approvals, and audit history. Email is stored only where necessary for authorized accounts, authentication, service requests, communication, or notifications; a teacher’s email must not be collected merely because that teacher borrows an asset.','Employee identification numbers are not currently stored. Firebase or the System may create an internal technical user identifier, but it is not an official payroll or employee number.','The System is not intended to routinely store student information. Student data is not a standard category and must not be introduced without a formally approved future function and policy update.','Asset and transaction information may include codes, QR codes, serial numbers, category, brand, model, condition, location, assigned person, assignment and return dates, transfers, repair and maintenance history, loss and damage reports, write-off and disposal records, and authorized photographs and documents.','IP addresses may be processed where technically available for authentication, hosting, security, human verification, audit logging, abuse prevention, troubleshooting, or incident investigation. The application does not claim always to record IP addresses. Limited browser, device, operating-system, app-version, language, login, and error information may be used for security, compatibility, troubleshooting, performance, and support.']),
s('5','purposes','Purposes of Processing',['Information may be processed to create and manage accounts, authenticate users, enforce role access, register and manage assets, record assignments, borrowing, returns and transfers, manage repair, maintenance and service requests, record approvals, conduct audits, investigate loss, theft, damage or misuse, generate authorized reports, protect the System, investigate incidents, provide support, meet recordkeeping duties, and improve stability and performance.']),
s('6','minimization','Data Minimization',['Only reasonably necessary information should be collected. Unnecessary sensitive or personal information must not be entered; free-text notes must not contain unrelated personal details; QR codes must not reveal unnecessary personal information; and access must follow least privilege.']),
s('7','ai-processing','AI Processing',['Authorized users may use OpenAI-powered functionality and data entered may be transmitted for processing. Users must not submit unnecessary confidential, sensitive, or personal data. AI output requires human review and must not make final employment, disciplinary, legal, financial, audit, or disposal decisions. Access follows role permissions and use may be logged for security and accountability.']),
s('8','basis','Organizational Basis',['KCS processes information where necessary for legitimate school administration, asset management, security, accountability, the performance of authorized duties, compliance with organizational responsibilities, and applicable legal or contractual obligations.']),
s('9','access','Access to Information',['Access may be provided only to authorized ICT personnel, system administrators, inventory personnel, management, approved auditors, and support personnel. Access is role-based and follows least-privilege principles.']),
s('10','providers','Third-Party Service Providers',['Firebase Authentication, Cloud Firestore, Firebase Storage, Firebase Hosting, Firebase Cloud Functions, Firebase Cloud Messaging where enabled, and OpenAI may process technical or application information required to deliver their services. KCS does not claim all data remains exclusively in Suriname.']),
s('11','security','Data Storage and Security',['Safeguards may include authentication, role-based authorization, Firestore and Storage Rules, secure connections, audit logging, account deactivation, least privilege, restricted administrative access, security monitoring, backup and recovery controls, and incident-response procedures. No system can guarantee absolute security.']),
s('12','retention','Retention Schedule',['Active accounts must be disabled promptly when access is no longer required. Deactivated accounts are reviewed after two years, after which unnecessary profile data may be deleted or anonymized. Names may remain where removal would undermine historical accountability. Incident logs may be retained longer during an active investigation and approved official records follow their applicable retention period.'],undefined,{headers:['Record type','Retention period'],rows:retentionRows.map(row=>[...row])}),
s('13','requests','Individual Requests',['Authorized individuals may request access, correction, processing clarification, account review, deletion or restriction where appropriate, or investigation of suspected misuse or unauthorized access by emailing servicedesk@kangoeroeschool.com. Identity verification may be required. Deletion cannot be guaranteed where information must remain for asset accountability, audit, transaction, security, or legal purposes.']),
s('14','incidents','Privacy and Security Incident Reporting',['Reports are first submitted to the KCS ICT Department. Technical reports are assessed by the ICT Manager, Head of Planning and Coordinator of the ICT Department, system administrator, or another designated ICT employee. Serious incidents involving personal data, employees, legal, financial, reputational, or significant organizational risk are escalated to the school director. KCS has not appointed a separate privacy officer.','ICT Support – Kangoeroe School · servicedesk@kangoeroeschool.com · +597 430870']),
s('15','changes','Changes to the Privacy Notice',['KCS may update this Notice. Every version shows its version number, effective date, and last-updated date. Material changes may be communicated in the System and may require acknowledgement.']),
s('16','contact','Contact Details',['St. Kangoeroe Community School, Edmundstraat 3–5, Uitvlucht, Paramaribo, Suriname. Telephone: +597 430870. General email: administratie@kangoeroeschool.com. Privacy and security: servicedesk@kangoeroeschool.com. Website: https://www.kangoeroecommunityschool.com. Facebook: Kangoeroe Community School.'])];
