import {AlertTriangle,CheckCircle2,Info,Search,XCircle,type LucideIcon} from 'lucide-react';
import {useId,type ButtonHTMLAttributes,type InputHTMLAttributes,type ReactNode,type SelectHTMLAttributes,type TextareaHTMLAttributes} from 'react';
export function Button({variant='primary',className='',...p}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger'}){return <button className={`btn btn-${variant} ${className}`} {...p}/>}
export function Card({children,className='',title,action}:{children:ReactNode;className?:string;title?:string;action?:ReactNode}){return <section className={`card ${className}`}>{(title||action)&&<header className="card-head">{title&&<h2>{title}</h2>}{action}</header>}{children}</section>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'success'|'warning'|'danger'|'info'|'neutral'}){return <span className={`badge badge-${tone}`}>{children}</span>}
export function Field({label,error,...p}:InputHTMLAttributes<HTMLInputElement>&{label:string;error?:string}){const id=useId(),errorId=`${id}-error`;return <label className="field" htmlFor={id}><span>{label}{p.required&&<b aria-hidden="true"> *</b>}</span><input id={id} aria-invalid={!!error} aria-describedby={error?errorId:undefined} {...p}/>{error&&<small id={errorId} className="field-error">{error}</small>}</label>}
export function SelectField({label,error,children,...p}:SelectHTMLAttributes<HTMLSelectElement>&{label:string;error?:string;children:ReactNode}){const id=useId(),errorId=`${id}-error`;return <label className="field" htmlFor={id}><span>{label}{p.required&&<b aria-hidden="true"> *</b>}</span><select id={id} aria-invalid={!!error} aria-describedby={error?errorId:undefined} {...p}>{children}</select>{error&&<small id={errorId} className="field-error">{error}</small>}</label>}
export function TextAreaField({label,error,...p}:TextareaHTMLAttributes<HTMLTextAreaElement>&{label:string;error?:string}){const id=useId(),errorId=`${id}-error`;return <label className="field" htmlFor={id}><span>{label}{p.required&&<b aria-hidden="true"> *</b>}</span><textarea id={id} aria-invalid={!!error} aria-describedby={error?errorId:undefined} {...p}/>{error&&<small id={errorId} className="field-error">{error}</small>}</label>}
export function SearchInput({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="search"><Search size={17}/><span className="sr-only">{placeholder}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
export function State({type,title,description,action}:{type:'empty'|'error'|'permission'|'offline';title:string;description:string;action?:ReactNode}){const Icon:LucideIcon=type==='error'||type==='permission'?XCircle:type==='offline'?AlertTriangle:type==='empty'?Info:CheckCircle2;return <div className="state"><span className={`state-icon ${type}`}><Icon/></span><h2>{title}</h2><p>{description}</p>{action}</div>}
export function Loader(){return <div className="skeleton-wrap" aria-label="Loading"><i/><i/><i/><i/></div>}
