import {useApp} from './context/AppContext';
const en={
  assets:'Assets',back:'Back to assets',save:'Save asset',saving:'Saving…',cancel:'Cancel',confirm:'Confirm',retry:'Try again',
  addTitle:'Add serialized asset',editTitle:'Edit serialized asset',formDescription:'Register identity, classification, ownership, purchase and technical details.',
  identity:'Identity',classification:'Classification',ownership:'Status and ownership',purchase:'Purchase and warranty',technical:'Technical information',media:'Documents and notes',
  codeGroup:'Code group',officialCode:'Official KCS code',name:'Asset name',description:'Description',category:'Category',subcategory:'Subcategory',itemType:'Item type',
  brand:'Brand',model:'Model',serial:'Serial number',barcode:'Barcode',qrPreparation:'QR code is prepared from the secure internal asset route.',
  status:'Status',condition:'Condition',location:'Location',department:'Department',assignedUser:'Assigned user',responsible:'Responsible employee',
  purchaseDate:'Purchase date',purchasePrice:'Purchase price',supplier:'Supplier',manufacturer:'Manufacturer',warrantyStart:'Warranty start',warrantyExpiry:'Warranty expiry',
  specifications:'Technical specifications',attachments:'Attachments',photos:'Photos',notes:'Notes',correction:'Administrative KCS code correction',correctionReason:'Mandatory correction reason',
  correctionWarning:'Changing an official code is exceptional. The previous code is preserved in history.',required:'This field is required.',invalidSerial:'Enter a valid serial number.',
  invalidPrefix:'Enter a valid KCS code using sequence 01–5000.',reasonRequired:'A correction reason is required.',invalidPrice:'Enter a valid non-negative price.',
  created:'Asset created',updated:'Asset updated',unsaved:'Discard unsaved changes?',notFound:'Asset not found',notFoundHelp:'The requested asset does not exist or is unavailable.',
  overview:'Overview',technicalDetails:'Technical details',assignmentHistory:'Assignment history',locationHistory:'Location history',borrowHistory:'Borrow history',
  repairHistory:'Repair history',maintenanceHistory:'Maintenance history',movementHistory:'Movement history',auditHistory:'Audit history',statusHistory:'Status history',
  documents:'Documents',accessories:'Accessories',lifecycle:'Lifecycle and disposal',internalId:'Internal asset ID',createdBy:'Created by',createdDate:'Created date',
  modifiedBy:'Last modified by',modifiedDate:'Last modified date',edit:'Edit',editAsset:'Edit asset',returnRecord:'Return to asset record',secureQrLabel:'Secure QR label',assign:'Assign',move:'Move',labels:'Labels',archive:'Archive',restore:'Restore',disposal:'Request disposal',history:'History',
  noRecords:'No records are available for this section.',historyTitle:'Asset history',eventType:'Event type',dateFrom:'Date from',dateTo:'Date to',user:'User',all:'All',print:'Print',details:'Details',
  assignmentTitle:'Assign asset',person:'Person',assignmentDate:'Assignment date',expectedEnd:'Expected end date',assignedBy:'Assigned by',signature:'Mock signature',assignmentBlocked:'This asset status does not allow assignment.',
  movementTitle:'Move asset',currentLocation:'Current location',destinationLocation:'Destination location',currentDepartment:'Current department',destinationDepartment:'Destination department',
  movementReason:'Movement reason',movementDate:'Movement date',approval:'Approval',attachmentsHelp:'Comma-separated mock file names.',
  labelsTitle:'Asset labels',labelSize:'Label size',copies:'Copies',single:'Single label',compact:'Compact',standard:'Standard',download:'Download mock label',secureRoute:'Secure asset-detail route',
  disposalTitle:'Start disposal request',disposalReason:'Disposal reason',assessment:'Technical assessment',estimatedValue:'Estimated value',method:'Recommended method',disposalHelp:'This creates a request only. Approval remains in the disposal module.',
  importTitle:'Import assets',upload:'Upload',parse:'Parse',validate:'Validate',preview:'Preview',commit:'Commit',result:'Result report',csvInput:'CSV or Excel-compatible text',parseFile:'Parse records',
  validRows:'Valid rows',invalidRows:'Invalid rows',sourceRow:'Source row',submitted:'Submitted value',normalized:'Normalized candidate',errorType:'Error type',explanation:'Explanation',recommendation:'Recommended correction',
  commitValid:'Commit valid records',importSuccess:'Import completed',permissionDenied:'Permission required',loading:'Loading asset…',submissionFailed:'The mock operation could not be completed.',
  success:'Operation completed successfully.',emptyHistory:'No matching history events.',before:'Before',after:'After',
  missingRequired:'A required value is missing.',missingRequiredFix:'Provide the required value.',invalidCode:'The KCS code is invalid.',invalidCodeFix:'Use a valid KCS prefix and sequence from 01 to 5000.',
  duplicateCode:'The normalized KCS code already exists.',duplicateCodeFix:'Choose the next unused official sequence.',duplicateSerial:'The serial number already exists.',duplicateSerialFix:'Verify the source record.',
  invalidCategory:'The category is not recognized.',invalidCategoryFix:'Use an active category.',invalidLocation:'The location is not recognized.',invalidLocationFix:'Use an active location.',
  invalidDepartment:'The department is not recognized.',invalidDepartmentFix:'Use an active department.'
} as const;
const nl:Record<keyof typeof en,string>={
  assets:'Middelen',back:'Terug naar middelen',save:'Middel opslaan',saving:'Opslaan…',cancel:'Annuleren',confirm:'Bevestigen',retry:'Opnieuw proberen',
  addTitle:'Geserialiseerd middel toevoegen',editTitle:'Geserialiseerd middel bewerken',formDescription:'Registreer identiteit, classificatie, verantwoordelijkheid, aankoop en technische gegevens.',
  identity:'Identiteit',classification:'Classificatie',ownership:'Status en verantwoordelijkheid',purchase:'Aankoop en garantie',technical:'Technische informatie',media:'Documenten en notities',
  codeGroup:'Codegroep',officialCode:'Officiële KCS-code',name:'Middelnaam',description:'Beschrijving',category:'Categorie',subcategory:'Subcategorie',itemType:'Middeltype',
  brand:'Merk',model:'Model',serial:'Serienummer',barcode:'Barcode',qrPreparation:'De QR-code wordt voorbereid vanuit de beveiligde interne middelroute.',
  status:'Status',condition:'Conditie',location:'Locatie',department:'Afdeling',assignedUser:'Toegewezen gebruiker',responsible:'Verantwoordelijke medewerker',
  purchaseDate:'Aankoopdatum',purchasePrice:'Aankoopprijs',supplier:'Leverancier',manufacturer:'Fabrikant',warrantyStart:'Start garantie',warrantyExpiry:'Einde garantie',
  specifications:'Technische specificaties',attachments:'Bijlagen',photos:"Foto's",notes:'Notities',correction:'Administratieve KCS-codecorrectie',correctionReason:'Verplichte correctiereden',
  correctionWarning:'Het wijzigen van een officiële code is uitzonderlijk. De vorige code blijft in de historie bewaard.',required:'Dit veld is verplicht.',invalidSerial:'Voer een geldig serienummer in.',
  invalidPrefix:'Voer een geldige KCS-code met volgnummer 01–5000 in.',reasonRequired:'Een correctiereden is verplicht.',invalidPrice:'Voer een geldige niet-negatieve prijs in.',
  created:'Middel aangemaakt',updated:'Middel bijgewerkt',unsaved:'Niet-opgeslagen wijzigingen weggooien?',notFound:'Middel niet gevonden',notFoundHelp:'Het gevraagde middel bestaat niet of is niet beschikbaar.',
  overview:'Overzicht',technicalDetails:'Technische details',assignmentHistory:'Toewijzingshistorie',locationHistory:'Locatiehistorie',borrowHistory:'Uitleenhistorie',
  repairHistory:'Reparatiehistorie',maintenanceHistory:'Onderhoudshistorie',movementHistory:'Mutatiehistorie',auditHistory:'Controlehistorie',statusHistory:'Statushistorie',
  documents:'Documenten',accessories:'Accessoires',lifecycle:'Levenscyclus en afvoer',internalId:'Interne middel-ID',createdBy:'Aangemaakt door',createdDate:'Aanmaakdatum',
  modifiedBy:'Laatst gewijzigd door',modifiedDate:'Laatste wijziging',edit:'Bewerken',editAsset:'Middel bewerken',returnRecord:'Terug naar middelrecord',secureQrLabel:'Beveiligd QR-label',assign:'Toewijzen',move:'Verplaatsen',labels:'Labels',archive:'Archiveren',restore:'Herstellen',disposal:'Afvoer aanvragen',history:'Historie',
  noRecords:'Voor dit onderdeel zijn geen records beschikbaar.',historyTitle:'Middelhistorie',eventType:'Gebeurtenistype',dateFrom:'Datum vanaf',dateTo:'Datum tot',user:'Gebruiker',all:'Alle',print:'Afdrukken',details:'Details',
  assignmentTitle:'Middel toewijzen',person:'Persoon',assignmentDate:'Toewijzingsdatum',expectedEnd:'Verwachte einddatum',assignedBy:'Toegewezen door',signature:'Mockhandtekening',assignmentBlocked:'Deze middelstatus staat toewijzing niet toe.',
  movementTitle:'Middel verplaatsen',currentLocation:'Huidige locatie',destinationLocation:'Bestemmingslocatie',currentDepartment:'Huidige afdeling',destinationDepartment:'Bestemmingsafdeling',
  movementReason:'Reden van verplaatsing',movementDate:'Mutatiedatum',approval:'Goedkeuring',attachmentsHelp:'Komma-gescheiden mockbestandsnamen.',
  labelsTitle:'Middellabels',labelSize:'Labelformaat',copies:'Aantal kopieën',single:'Enkel label',compact:'Compact',standard:'Standaard',download:'Mocklabel downloaden',secureRoute:'Beveiligde middelroute',
  disposalTitle:'Afvoerverzoek starten',disposalReason:'Reden van afvoer',assessment:'Technische beoordeling',estimatedValue:'Geschatte waarde',method:'Aanbevolen methode',disposalHelp:'Dit maakt alleen een verzoek. Goedkeuring blijft onderdeel van de afvoermodule.',
  importTitle:'Middelen importeren',upload:'Uploaden',parse:'Parseren',validate:'Valideren',preview:'Voorbeeld',commit:'Bevestigen',result:'Resultaatrapport',csvInput:'CSV- of Excel-compatibele tekst',parseFile:'Records parseren',
  validRows:'Geldige rijen',invalidRows:'Ongeldige rijen',sourceRow:'Bronrij',submitted:'Ingediende waarde',normalized:'Genormaliseerde kandidaat',errorType:'Fouttype',explanation:'Uitleg',recommendation:'Aanbevolen correctie',
  commitValid:'Geldige records vastleggen',importSuccess:'Import voltooid',permissionDenied:'Toestemming vereist',loading:'Middel laden…',submissionFailed:'De mockbewerking kon niet worden voltooid.',
  success:'Bewerking succesvol voltooid.',emptyHistory:'Geen overeenkomende historiegebeurtenissen.',before:'Voor',after:'Na',
  missingRequired:'Een verplichte waarde ontbreekt.',missingRequiredFix:'Vul de verplichte waarde in.',invalidCode:'De KCS-code is ongeldig.',invalidCodeFix:'Gebruik een geldige KCS-prefix en volgnummer van 01 tot 5000.',
  duplicateCode:'De genormaliseerde KCS-code bestaat al.',duplicateCodeFix:'Kies het volgende ongebruikte officiële volgnummer.',duplicateSerial:'Het serienummer bestaat al.',duplicateSerialFix:'Controleer het bronrecord.',
  invalidCategory:'De categorie wordt niet herkend.',invalidCategoryFix:'Gebruik een actieve categorie.',invalidLocation:'De locatie wordt niet herkend.',invalidLocationFix:'Gebruik een actieve locatie.',
  invalidDepartment:'De afdeling wordt niet herkend.',invalidDepartmentFix:'Gebruik een actieve afdeling.'
};
export type AssetCopyKey=keyof typeof en;
export const assetCopy={en,nl};
export function useAssetT(){const{language}=useApp();return(key:AssetCopyKey)=>assetCopy[language][key]}
