import {ArrowDown,ArrowUp,Edit3,Plus,Power,Trash2} from 'lucide-react';
import {useState,type FormEvent} from 'react';
import {Badge,Button,Field} from '../ui';
import {ConfirmDialog,Dialog,MutationFeedback} from '../WorkflowUi';
import {useApp} from '../../context/AppContext';
import type {CodeGroup} from '../../data/contracts';
import {useMockSnapshot,useRepository} from '../../data/mockRepository';
import {LocationTypesSettings} from './LocationTypesSettings';

type Feedback={status:'idle'|'loading'|'success'|'error';message:string};
function CodeGroupForm({value,onClose}:{value?:CodeGroup;onClose:()=>void}){const repository=useRepository(),[feedback,setFeedback]=useState<Feedback>({status:'idle',message:''});async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const result=await repository.execute({action:value?'codeGroup.edit':'codeGroup.create',entityId:value?.id,values:{name:data.get('name'),prefix:data.get('prefix'),minimumNumber:Number(data.get('minimumNumber')),maximumNumber:Number(data.get('maximumNumber')),nextAvailableNumber:Number(data.get('nextAvailableNumber'))}});setFeedback({status:result.ok?'success':'error',message:result.message});if(result.ok)onClose()}return <form className="workflow-form" onSubmit={save}><Field name="name" label="Name" defaultValue={value?.name} required/><Field name="prefix" label="Prefix" defaultValue={value?.prefix} required/><Field name="minimumNumber" type="number" min="0" label="Minimum number" defaultValue={value?.minimumNumber??1} required/><Field name="maximumNumber" type="number" min="1" label="Maximum number" defaultValue={value?.maximumNumber??5000} required/><Field name="nextAvailableNumber" type="number" min="0" label="Next available number" defaultValue={value?.nextAvailableNumber??1} required/><div className="wide"><MutationFeedback {...feedback}/><div className="actions"><Button type="submit">Save code group</Button><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button></div></div></form>}

function CodeGroupsSettings(){const repository=useRepository(),snapshot=useMockSnapshot(),[editing,setEditing]=useState<CodeGroup|null|undefined>(undefined),[deleting,setDeleting]=useState<CodeGroup|null>(null),[feedback,setFeedback]=useState<Feedback>({status:'idle',message:''});const groups=[...snapshot.codeGroups].sort((a,b)=>a.sortOrder-b.sortOrder);async function run(action:'codeGroup.activate'|'codeGroup.deactivate'|'codeGroup.reorder'|'codeGroup.delete',group:CodeGroup,values?:Record<string,unknown>){const result=await repository.execute({action,entityId:group.id,values});setFeedback({status:result.ok?'success':'error',message:result.message})}return <div><div className="section-toolbar"><div><h3>Code groups</h3><p>Configure official asset-code ranges and allocation.</p></div><Button onClick={()=>setEditing(null)}><Plus/>Add group</Button></div><MutationFeedback {...feedback}/><div className="location-type-list">{groups.map((group,index)=>{const used=snapshot.assets.some(x=>x.codePrefix===group.prefix);return <article key={group.id}><span className="location-type-order">{group.sortOrder}</span><div><strong>{group.name} <code>{group.prefix}</code></strong><small>Range {group.minimumNumber}–{group.maximumNumber} · Next {group.nextAvailableNumber}</small></div><Badge tone={group.isActive?'success':'neutral'}>{group.isActive?'Active':'Inactive'}</Badge><div className="location-type-actions"><Button variant="ghost" disabled={index===0} onClick={()=>run('codeGroup.reorder',group,{direction:-1})}><ArrowUp/></Button><Button variant="ghost" disabled={index===groups.length-1} onClick={()=>run('codeGroup.reorder',group,{direction:1})}><ArrowDown/></Button><Button variant="ghost" onClick={()=>setEditing(group)}><Edit3/></Button><Button variant="ghost" onClick={()=>run(group.isActive?'codeGroup.deactivate':'codeGroup.activate',group)}><Power/></Button><Button variant="danger" onClick={()=>setDeleting(group)} title={used?'Used groups cannot be deleted; deactivate instead.':'Delete group'}><Trash2/></Button></div></article>})}</div><Dialog open={editing!==undefined} title={editing?'Edit code group':'Add code group'} onClose={()=>setEditing(undefined)}>{editing!==undefined&&<CodeGroupForm value={editing||undefined} onClose={()=>setEditing(undefined)}/>}</Dialog><ConfirmDialog open={!!deleting} title="Delete code group" description={deleting&&snapshot.assets.some(x=>x.codePrefix===deleting.prefix)?'This group is in use and cannot be deleted. Deactivate it instead.':'This permanently removes the code group.'} confirmLabel="Delete" danger onClose={()=>setDeleting(null)} onConfirm={async()=>{if(deleting)await run('codeGroup.delete',deleting)}}/></div>}

export function MasterDataSettings(){const {user}=useApp(),[tab,setTab]=useState<'locations'|'codes'>('locations');if(user?.role!=='administrator')return <div className="state"><h3>Administrator access required</h3><p>Only administrators can manage location and code groups.</p></div>;return <div className="master-data-settings"><div className="subnav" role="tablist"><button type="button" className={tab==='locations'?'active':''} onClick={()=>setTab('locations')} role="tab" aria-selected={tab==='locations'}>Locations</button><button type="button" className={tab==='codes'?'active':''} onClick={()=>setTab('codes')} role="tab" aria-selected={tab==='codes'}>Code Groups</button></div>{tab==='locations'?<LocationTypesSettings/>:<CodeGroupsSettings/>}</div>}
