export interface ExportColumn<T>{id:string;label:string;value:(row:T)=>unknown;authorized?:boolean}
export interface ExportMetadata{generatedAt:string;generatedBy:string;title:string}
const safe=(value:unknown)=>String(value??'');
export const neutralizeSpreadsheetFormula=(value:unknown)=>{
  const text=safe(value);
  return /^[=+\-@]/.test(text)?`'${text}`:text;
};
const csvCell=(value:unknown)=>`"${neutralizeSpreadsheetFormula(value).replaceAll('"','""')}"`;
const xml=(value:unknown)=>safe(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const allowed=<T,>(columns:ExportColumn<T>[])=>columns.filter(column=>column.authorized!==false);
export function createCsv<T>(rows:T[],columns:ExportColumn<T>[],metadata:ExportMetadata){
  const selected=allowed(columns);
  return[[metadata.title],[`Generated ${metadata.generatedAt}`],[`Generated by ${metadata.generatedBy}`],[],selected.map(column=>column.label),...rows.map(row=>selected.map(column=>column.value(row)))].map(line=>line.map(csvCell).join(',')).join('\r\n');
}
export function createSpreadsheetXml<T>(rows:T[],columns:ExportColumn<T>[],metadata:ExportMetadata){
  const selected=allowed(columns),row=(values:unknown[])=>`<Row>${values.map(value=>`<Cell><Data ss:Type="String">${xml(value)}</Data></Cell>`).join('')}</Row>`;
  return`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Export"><Table>${row([metadata.title])}${row([`Generated ${metadata.generatedAt}`])}${row([`Generated by ${metadata.generatedBy}`])}${row([])}${row(selected.map(column=>column.label))}${rows.map(item=>row(selected.map(column=>column.value(item)))).join('')}</Table></Worksheet></Workbook>`;
}
export function createPrintHtml<T>(rows:T[],columns:ExportColumn<T>[],metadata:ExportMetadata){
  const selected=allowed(columns);
  return`<!doctype html><html><head><meta charset="utf-8"><title>${xml(metadata.title)}</title><style>body{font:14px system-ui;padding:24px;color:#101828}.brand-header{display:grid;grid-template-columns:1fr 1fr;gap:10px 24px;align-items:center;border-bottom:2px solid #155eef;padding-bottom:12px;margin-bottom:18px}.brand{display:flex;align-items:center;gap:10px}.brand.right{justify-content:flex-end;text-align:right}.brand img{width:42px;height:42px;object-fit:contain}.brand span{display:grid}.meta{grid-column:1/-1;margin:0;color:#344054}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bbb;padding:7px;text-align:left}small{color:#555}</style></head><body><header class="brand-header"><div class="brand"><img src="/aims-logo-blue.png" alt=""><span><strong>AIMS</strong><small>Asset &amp; Inventory System</small></span></div><div class="brand right"><span><strong>St. Kangoeroe Community School</strong><small>KCS</small></span><img src="/kcs-school-logo.jpg" alt=""></div><p class="meta"><strong>Afgedrukt door:</strong> ${xml(metadata.generatedBy)} · <strong>Datum en tijd:</strong> ${xml(metadata.generatedAt)}</p></header><h1>${xml(metadata.title)}</h1><table><thead><tr>${selected.map(column=>`<th>${xml(column.label)}</th>`).join('')}</tr></thead><tbody>${rows.map(item=>`<tr>${selected.map(column=>`<td>${xml(column.value(item))}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`;
}
export function downloadText(name:string,contents:string,type:string){
  const url=URL.createObjectURL(new Blob([contents],{type})),anchor=document.createElement('a');
  anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);
}
