export interface ExportColumn<T>{id:string;label:string;value:(row:T)=>unknown;authorized?:boolean}
export interface ExportMetadata{generatedAt:string;generatedBy:string;title:string}
const safe=(value:unknown)=>String(value??'');
export const neutralizeSpreadsheetFormula=(value:unknown)=>{
  const text=safe(value);
  return /^[=+\-@]/.test(text)?`'${text}`:text;
};
const csvCell=(value:unknown)=>`"${neutralizeSpreadsheetFormula(value).replaceAll('"','""')}"`;
const xml=(value:unknown)=>safe(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const allowed=<T,>(columns:ExportColumn<T>[])=>columns.filter(column=>column.authorized!==false);
export function createCsv<T>(rows:T[],columns:ExportColumn<T>[],metadata:ExportMetadata){
  const selected=allowed(columns);
  return[
    [metadata.title],[`Generated ${metadata.generatedAt}`],[`Generated by ${metadata.generatedBy}`],[],
    selected.map(column=>column.label),
    ...rows.map(row=>selected.map(column=>column.value(row)))
  ].map(line=>line.map(csvCell).join(',')).join('\r\n');
}
export function createSpreadsheetXml<T>(rows:T[],columns:ExportColumn<T>[],metadata:ExportMetadata){
  const selected=allowed(columns),row=(values:unknown[])=>`<Row>${values.map(value=>`<Cell><Data ss:Type="String">${xml(value)}</Data></Cell>`).join('')}</Row>`;
  return`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Export"><Table>${row([metadata.title])}${row([`Generated ${metadata.generatedAt}`])}${row([`Generated by ${metadata.generatedBy}`])}${row([])}${row(selected.map(column=>column.label))}${rows.map(item=>row(selected.map(column=>column.value(item)))).join('')}</Table></Worksheet></Workbook>`;
}
export function createPrintHtml<T>(rows:T[],columns:ExportColumn<T>[],metadata:ExportMetadata){
  const selected=allowed(columns);
  return`<!doctype html><html><head><meta charset="utf-8"><title>${xml(metadata.title)}</title><style>body{font:14px system-ui;padding:24px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bbb;padding:7px;text-align:left}small{color:#555}</style></head><body><h1>${xml(metadata.title)}</h1><small>Generated ${xml(metadata.generatedAt)} · ${xml(metadata.generatedBy)}</small><table><thead><tr>${selected.map(column=>`<th>${xml(column.label)}</th>`).join('')}</tr></thead><tbody>${rows.map(item=>`<tr>${selected.map(column=>`<td>${xml(column.value(item))}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`;
}
export function downloadText(name:string,contents:string,type:string){
  const url=URL.createObjectURL(new Blob([contents],{type})),anchor=document.createElement('a');
  anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);
}
